/**
 * What a business asks its clients after they book.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * ONE DECLARATION.
 *
 * The shape this replaces was written out five times — in the repository, the
 * contact drawer, the settings panel, the public form page and the website
 * block — with no shared source. They had already drifted: the repository's
 * union allows `checkbox`, `tel` and `email`, which nothing produces and only
 * some renderers handle. A form definition read by six surfaces cannot be
 * described in six places.
 *
 * ONE LANGUAGE.
 *
 * The old fields carried `label_en`, `label_es` and `label_he` because the
 * templates were a SHARED library: one row served every business, so it had to
 * speak every language. A generated form belongs to one business, is written in
 * that business's language, and is read by that business's clients. Two thirds
 * of every label disappears with the sharing.
 *
 * The trade is real and worth stating: a business serving clients in two
 * languages now has one intake in one language. That was already true in
 * practice — the old form picked its labels from the reader's locale, so a
 * Hebrew business's English-speaking client saw questions the owner had never
 * read. One deliberate language beats a translation nobody wrote.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * @module lib/business-os/intake/types
 */

/**
 * How an answer is collected.
 *
 * Deliberately plain-language rather than a schema vocabulary: these names are
 * shown to the business owner when they override an inferred type, so they read
 * as choices rather than as data types. There is no `string`, `enum` or `array`
 * anywhere a non-technical user can reach.
 */
export const INTAKE_QUESTION_TYPES = [
  'short_text',
  'long_text',
  'yes_no',
  'single_choice',
  'multi_choice',
  'date',
  'number',
  'file',
] as const;

export type IntakeQuestionType = (typeof INTAKE_QUESTION_TYPES)[number];

/** One answer a client may pick. `id` is stable; `label` is the visible words. */
export interface IntakeQuestionOption {
  id: string;
  label: string;
}

/**
 * Show this question only when an earlier one was answered a particular way.
 *
 * Generated by the model, never authored by the owner — the review screen draws
 * it as indentation under its parent and offers the same five actions on it as
 * on any other question. There is no rule builder, and this shape is
 * deliberately too small to grow into one: one question, one value, equality.
 * Anything more expressive is a form builder, which is the thing this is not.
 */
export interface IntakeQuestionCondition {
  questionId: string;
  equals: string | boolean;
}

export interface IntakeQuestion {
  /**
   * Stable for the life of the question.
   *
   * NOT derived from the label, which is the mistake the old `key` field made:
   * relabelling a question would orphan every answer already given to it, and
   * `showIf` would point at a question that no longer exists under that name.
   */
  id: string;
  /** In the business's own language. */
  label: string;
  /** An optional sentence under the question. Absent far more often than not. */
  help?: string;
  type: IntakeQuestionType;
  required: boolean;
  /** Present for `single_choice` and `multi_choice`, meaningless otherwise. */
  options?: IntakeQuestionOption[];
  /** For `file`. Absent means one. */
  maxFiles?: number;
  showIf?: IntakeQuestionCondition;
}

export type IntakeFormStatus = 'draft' | 'published' | 'archived';

/**
 * Where a form's questions came from.
 *
 * Kept so a later reader can tell a generated form from a hand-built one, and
 * an LLM-written form from the deterministic fallback — the distinction
 * `WebsiteGenerationService` reports as `contentSource`, and the reason a silent
 * fallback cannot pass itself off as a successful generation.
 */
export interface IntakeFormProvenance {
  source: 'llm' | 'fallback' | 'manual';
  model?: string;
  vertical?: string | null;
  subVertical?: string | null;
  serviceIds?: string[];
}

export interface IntakeForm {
  id: string;
  user_id: string;
  version: number;
  status: IntakeFormStatus;
  questions: IntakeQuestion[];
  generated_at: string | null;
  generated_from: IntakeFormProvenance | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * A completed intake, as stored on the booking.
 *
 * `questions` is a SNAPSHOT, and that is the whole point of it. A form is
 * edited and republished over time; without the questions recorded beside the
 * answers, a submission from three versions ago renders as a list of values
 * with nothing to say what was asked. `form_id` and `version` say which form it
 * was; the snapshot means the answer is readable even so.
 */
export interface IntakeSubmission {
  form_id: string;
  version: number;
  questions: IntakeQuestion[];
  responses: Record<string, unknown>;
}

const TYPES = new Set<string>(INTAKE_QUESTION_TYPES);

export function isIntakeQuestionType(value: unknown): value is IntakeQuestionType {
  return typeof value === 'string' && TYPES.has(value);
}

/** Choice questions need options; nothing else has any use for them. */
export function questionTakesOptions(type: IntakeQuestionType): boolean {
  return type === 'single_choice' || type === 'multi_choice';
}

/**
 * The questions a client should actually be shown, given what they have
 * answered so far.
 *
 * Conditions are evaluated against answers, not against other conditions: a
 * question whose parent is itself hidden is hidden too, because its parent's
 * answer is absent rather than matching. That falls out of the equality check
 * and needs no separate rule — which is why the condition shape has no nesting.
 */
export function visibleQuestions(
  questions: IntakeQuestion[],
  answers: Record<string, unknown>
): IntakeQuestion[] {
  return questions.filter(question => {
    if (!question.showIf) return true;
    return answers[question.showIf.questionId] === question.showIf.equals;
  });
}

/**
 * What a client may attach to an intake answer.
 *
 * Declared here because two places need it and they must not drift: the upload
 * route enforces it, and the file picker on the public page uses it so someone
 * learns their file is unwelcome BEFORE waiting for an upload to fail.
 *
 * The server is still the authority — `accept` is a hint the browser may ignore
 * and a caller can bypass entirely.
 */
export const INTAKE_UPLOAD_MIME_TYPES = [
  // Images
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
  'image/gif',
  'image/tiff',
  'image/bmp',
  // Documents
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.oasis.opendocument.spreadsheet',
  'application/rtf',
  'text/plain',
  'text/csv',
] as const;

/** 10MB. Generous for a photograph or a scan, mean enough that a video is refused. */
export const INTAKE_UPLOAD_MAX_BYTES = 10 * 1024 * 1024;

/**
 * For the picker's `accept`. Extensions are included alongside the mime types
 * because some systems report an empty or wrong type for Office files, and an
 * `accept` list of mime types alone then hides the very file being asked for.
 */
export const INTAKE_UPLOAD_ACCEPT = [
  ...INTAKE_UPLOAD_MIME_TYPES,
  '.doc',
  '.docx',
  '.xls',
  '.xlsx',
  '.ppt',
  '.pptx',
  '.odt',
  '.ods',
  '.rtf',
  '.csv',
  '.txt',
  '.heic',
].join(',');
