// lib/repositories/BosCronRunRepository.ts
// Writes to `bos_cron_runs`, the run record of the Business OS scheduled jobs
// (admin reorganisation slice 5, part B; migration 20261011_bos_cron_runs.sql).
//
// WHO MAY CALL IT: only `lib/cron/cronRunRecorder.ts` (a source guard in
// lib/repositories/__tests__/BosCronRunRepository.test.ts enforces it). The
// recorder calls it only after proving the request is Vercel's own cron call
// (SA SC-1), so no caller-supplied value ever reaches a write.
//
// SERVICE ROLE, AND NO user_id FILTER, ON PURPOSE. `bos_cron_runs` holds no
// tenant data: no user id, no business id, no owner text — a job name, times,
// a fixed outcome word, an error CLASS and numeric counts (the database refuses
// anything else: SA SC-3). CLAUDE.md rule 4 (`.eq('user_id', userId)`) has
// nothing to scope. RLS is on with no policy; only the service role holds
// privileges (the migration's access check proves it).
//
// THE TABLE MAY NOT EXIST YET (FR-R8). The code deploys before or after the
// hand-applied migration; `isMissingRelationError` lets the recorder tell "not
// installed yet" from a real failure. That is the deliberate exception to the
// new-repository skill's "stop if the table does not exist".
//
// Every method takes an optional AbortSignal (the recorder bounds each write
// with a deadline) and never throws: it returns `{ data, error }`.

import type { SupabaseClient } from '@supabase/supabase-js';
import { supabaseServer as defaultSupabase } from '@/lib/supabaseServer';
import { createLogger, type Logger } from '@/lib/logger';
import type { AgentRepositoryResult as RepositoryResult } from './types';
import { isMissingRelationError } from './supabaseErrorCodes';

export type BosCronRunOutcome = 'running' | 'succeeded' | 'partial' | 'failed';
export type BosCronRunErrorClass = 'http_error' | 'exception' | 'timeout';
export type BosCronRunSource = 'vercel_cron' | 'other';

export interface StartBosCronRunInput {
  /** Generated by the recorder (SA SC-2), never caller-supplied. */
  id: string;
  job: string;
  source: BosCronRunSource;
  startedAt: Date;
  deadlineAt: Date;
}

export interface FinishBosCronRunInput {
  finishedAt: Date;
  outcome: Exclude<BosCronRunOutcome, 'running'>;
  durationMs: number;
  httpStatus: number | null;
  errorClass: BosCronRunErrorClass | null;
  /** Numbers only; the database refuses anything else. */
  counts: Record<string, number>;
}

export interface WriteOptions {
  signal?: AbortSignal;
}

interface SupabaseErrorLike {
  code?: string;
  message?: string;
}

export { isMissingRelationError };

function asError(error: unknown): Error {
  if (error instanceof Error) return error;
  const e = (error ?? {}) as SupabaseErrorLike;
  const wrapped = new Error(e.message ?? 'Supabase error') as Error & { code?: string };
  if (e.code) wrapped.code = e.code;
  return wrapped;
}

type AbortableQuery<T> = PromiseLike<T> & { abortSignal?: (signal: AbortSignal) => AbortableQuery<T> };

function withSignal<T>(query: AbortableQuery<T>, signal?: AbortSignal): PromiseLike<T> {
  return signal && typeof query.abortSignal === 'function' ? query.abortSignal(signal) : query;
}

export class BosCronRunRepository {
  private supabase: SupabaseClient;
  private logger: Logger;

  constructor(supabaseClient?: SupabaseClient) {
    // Intentionally the service role: the table has no tenant, and no user
    // session may read or write it (RLS on, no policy).
    this.supabase = supabaseClient || defaultSupabase;
    this.logger = createLogger({ service: 'BosCronRunRepository' });
  }

  /** Insert the "running" row. An explicit field allow-list (tenant-isolation-guard step 3). */
  async startRun(input: StartBosCronRunInput, options: WriteOptions = {}): Promise<RepositoryResult<true>> {
    try {
      const query = this.supabase.from('bos_cron_runs').insert({
        id: input.id,
        job: input.job,
        source: input.source,
        started_at: input.startedAt.toISOString(),
        deadline_at: input.deadlineAt.toISOString(),
      }) as unknown as AbortableQuery<{ error: unknown }>;
      const { error } = await withSignal(query, options.signal);
      if (error) return { data: null, error: asError(error) };
      return { data: true, error: null };
    } catch (error) {
      return { data: null, error: asError(error) };
    }
  }

  /**
   * Record the outcome. Only a row still "running" is updated, so a late or
   * repeated finish can never overwrite a finished run. Returns how many rows
   * were updated (SA-4): 1 = recorded; 0 = no running row matched (the start
   * never committed, or the row was already finished), which is not an error.
   */
  async finishRun(id: string, input: FinishBosCronRunInput, options: WriteOptions = {}): Promise<RepositoryResult<number>> {
    try {
      const query = this.supabase
        .from('bos_cron_runs')
        .update({
          finished_at: input.finishedAt.toISOString(),
          outcome: input.outcome,
          duration_ms: Math.max(0, Math.round(input.durationMs)),
          http_status: input.httpStatus,
          error_class: input.errorClass,
          counts: input.counts,
        })
        .eq('id', id)
        .eq('outcome', 'running')
        .select('id') as unknown as AbortableQuery<{ data: unknown; error: unknown }>;
      const { data, error } = await withSignal(query, options.signal);
      if (error) return { data: null, error: asError(error) };
      return { data: Array.isArray(data) ? data.length : 0, error: null };
    } catch (error) {
      return { data: null, error: asError(error) };
    }
  }

  /** Retention (OQ-6): remove runs that started before the cutoff. */
  async deleteRunsStartedBefore(cutoff: Date, options: WriteOptions = {}): Promise<RepositoryResult<true>> {
    try {
      const query = this.supabase
        .from('bos_cron_runs')
        .delete()
        .lt('started_at', cutoff.toISOString()) as unknown as AbortableQuery<{ error: unknown }>;
      const { error } = await withSignal(query, options.signal);
      if (error) {
        this.logger.warn({ code: (error as SupabaseErrorLike).code }, 'Pruning old cron runs failed');
        return { data: null, error: asError(error) };
      }
      return { data: true, error: null };
    } catch (error) {
      return { data: null, error: asError(error) };
    }
  }
}

export const bosCronRunRepository = new BosCronRunRepository();
