/**
 * Refunds — one endpoint for every surface.
 *
 * The payments tab, the invoices tab and the CRM contact drawer all post here.
 * They previously hit two different backends with different guarantees, which is
 * how the two implementations drifted apart; a caller now names what it is
 * looking at and the server works out the payment behind it.
 *
 *   POST /api/payments/refunds        issue a refund
 *   GET  /api/payments/refunds?transaction_id=…   how much is refundable, and why not
 *
 * @module app/api/payments/refunds
 */

import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { getUser } from '@/lib/auth';
import { createLogger } from '@/lib/logger';
import { AuditTrailService } from '@/lib/services/AuditTrailService';
import { getRefundability, refund, resolveRefundTarget } from '@/lib/payments/RefundService';

const logger = createLogger({ module: 'RefundsAPI' });
const auditTrail = AuditTrailService.getInstance();

const RefundSchema = z
  .object({
    transaction_id: z.string().uuid().optional(),
    invoice_id: z.string().uuid().optional(),
    booking_id: z.string().uuid().optional(),
    /** Major units. Omitted means everything still remaining. */
    amount: z.number().positive().optional(),
    reason: z.string().max(500).optional(),
    /**
     * Stable for one user intent, so a double click or a retry after a timeout
     * cannot become a second refund. Generated by the client per modal opening.
     */
    client_request_id: z.string().min(8).max(200).optional(),
  })
  .refine(
    body => !!(body.transaction_id || body.invoice_id || body.booking_id),
    { message: 'One of transaction_id, invoice_id or booking_id is required' }
  );

/** Which HTTP status each refusal deserves. */
const STATUS_FOR: Record<string, number> = {
  NOT_FOUND: 404,
  NOT_REFUNDABLE: 409,
  // The request was valid; the server cannot safely act on it yet.
  ACCOUNT_UNRESOLVED: 409,
  BALANCE_INSUFFICIENT: 409,
  NOTHING_REMAINING: 409,
  EXCEEDS_REMAINING: 400,
  NOT_POSITIVE: 400,
  PROCESSOR_ERROR: 502,
};

export async function POST(request: NextRequest) {
  const correlationId = request.headers.get('x-correlation-id') || crypto.randomUUID();
  const requestLogger = logger.child({ correlationId });

  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const parsed = RefundSchema.safeParse(await request.json());
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: 'Invalid request', details: parsed.error.errors },
        { status: 400 }
      );
    }

    const body = parsed.data;

    // userId comes from the session and is never taken from the body — it is
    // what scopes the lookup, so a caller cannot refund someone else's payment
    // by naming its id.
    const target = await resolveRefundTarget({
      userId: user.id,
      transactionId: body.transaction_id,
      invoiceId: body.invoice_id,
      bookingId: body.booking_id,
    });

    if ('error' in target) {
      return NextResponse.json(
        { success: false, error: target.message, code: target.error },
        { status: STATUS_FOR[target.error] ?? 400 }
      );
    }

    const result = await refund({
      userId: user.id,
      transactionId: target.transactionId,
      amount: body.amount,
      reason: body.reason,
      source: 'app',
      initiatedBy: user.id,
      clientRequestId: body.client_request_id,
    });

    if (!result.ok) {
      requestLogger.warn(
        { userId: user.id, transactionId: target.transactionId, code: result.code },
        'Refund refused'
      );
      return NextResponse.json(
        { success: false, error: result.message, code: result.code, remaining: result.remaining },
        { status: STATUS_FOR[result.code] ?? 400 }
      );
    }

    // Money leaving the business is about as material as this product gets, so
    // it is audited at `critical` — and never allowed to fail the request.
    auditTrail
      .log({
        action: 'PAYMENT_REFUNDED',
        entityType: 'payment_transaction',
        entityId: target.transactionId,
        userId: user.id,
        severity: 'critical',
        changes: {
          refundId: result.refundId,
          processorRefundId: result.processorRefundId,
          amount: result.amount,
          currency: result.currency,
          replayed: result.replayed,
        },
        request,
      })
      .catch(err => requestLogger.error({ err }, 'Audit failed (non-blocking)'));

    return NextResponse.json({ success: true, data: result });
  } catch (error) {
    requestLogger.error({ err: error }, 'Refund request failed');
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * What the UI needs to render an honest button: the real maximum, and the real
 * reason when there is none. Without this the client has to guess, which is why
 * the existing modal's cap can be bypassed by posting directly.
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const transactionId = new URL(request.url).searchParams.get('transaction_id');
    if (!transactionId) {
      return NextResponse.json(
        { success: false, error: 'transaction_id is required' },
        { status: 400 }
      );
    }

    return NextResponse.json({
      success: true,
      data: await getRefundability(user.id, transactionId),
    });
  } catch (error) {
    logger.error({ err: error }, 'Refundability check failed');
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}
