/**
 * Refunds — one endpoint for every surface.
 *
 * The payments tab, the invoices tab and the CRM contact drawer all post here.
 * They previously hit two different backends with different guarantees, which is
 * how the two implementations drifted apart; a caller now names what it is
 * looking at and the server works out the payment behind it.
 *
 *   POST /api/payments/refunds        issue a refund
 *   GET  /api/payments/refunds?transaction_id=…   how much is refundable, and why not
 *
 * @module app/api/payments/refunds
 */

import { NextRequest, NextResponse } from 'next/server';
import { notifyRefund } from '@/lib/payments/notifyRefund';
import { syncBookingsForTransactions } from '@/lib/payments/syncBookingPaymentState';
import { z } from 'zod';
import { getUser } from '@/lib/auth';
import Stripe from 'stripe';
import { supabaseServer } from '@/lib/supabaseServer';
import { cancelPlan } from '@/lib/payments/cancelPlan';
import { STOP_REASONS, type StopReason } from '@/lib/business-os/cancellationReasons';
import { cancelBooking } from '@/lib/services/BookingLifecycleService';
import { createLogger } from '@/lib/logger';
import { AuditTrailService } from '@/lib/services/AuditTrailService';
import {
  getRefundability,
  refund,
  refundGroup,
  resolveRefundTargets,
} from '@/lib/payments/RefundService';

const logger = createLogger({ module: 'RefundsAPI' });
const auditTrail = AuditTrailService.getInstance();

const RefundSchema = z
  .object({
    transaction_id: z.string().uuid().optional(),
    invoice_id: z.string().uuid().optional(),
    booking_id: z.string().uuid().optional(),
    /** Major units. Omitted means everything still remaining. */
    amount: z.number().positive().optional(),
    /*
     * BOTH REQUIRED, by product decision.
     *
     * `reason` is the canned key the refund-pattern detector groups on and the
     * drawer renders in the reader's language; `reason_note` is the sentence that
     * key cannot carry. The dialog used to send one or the other, so a refund was
     * either countable or explained and never both.
     *
     * Only `RefundModal` posts here, so requiring them breaks no other caller —
     * the chat and the internal refund paths call `refundGroup` directly.
     */
    reason: z.string().min(1).max(500),
    reason_note: z.string().min(1).max(1000),
    /**
     * Stable for one user intent, so a double click or a retry after a timeout
     * cannot become a second refund. Generated by the client per modal opening.
     */
    client_request_id: z.string().min(8).max(200).optional(),
    /**
     * Tell the client their money is coming back.
     *
     * Collected by the refund dialog on every surface since it was written, and
     * for just as long dropped on the floor here — so whether a client heard
     * about their refund depended on which button the owner pressed.
     *
     * Defaults to FALSE, unlike the booking route's true: a refund the client
     * has not been promised is the owner's to announce.
     */
    notify_contact: z.boolean().optional(),
    /**
     * Record a refund the business made itself, outside any processor.
     *
     * A bank transfer sent back, cash returned. Accepted only for money that
     * never went through a processor — RefundService checks the transaction's
     * `processor_type` and refuses otherwise, because recording a refund by
     * hand against a live card charge would close the invoice while the client
     * was still out of pocket.
     */
    manual: z.boolean().optional(),
    /**
     * One payment, or everything collected against the thing named.
     *
     * Never inferred. A booking with a deposit and a balance, or a plan with
     * twelve periods, has no single obvious answer — and the version that
     * guessed returned one twelfth of a plan and reported success.
     */
    scope: z.enum(['payment', 'all']).optional(),
    /**
     * Stop the payment plan behind this booking as well.
     *
     * Refunding a plan payment does not stop the plan — the client is charged
     * again next period. Never inferred, because stopping and refunding are
     * separate decisions with different right answers, but offered wherever a
     * plan is actually live.
     */
    stop_plan: z.boolean().optional(),
    /**
     * Cancel the booking this money paid for, as well.
     *
     * The switch existed on the refund dialog and reached nothing. It was held in
     * the modal's state and handed to `onSuccess(deleteBooking)`, and all four
     * callers are written `onSuccess={() => ...}` — so the flag was passed to a
     * function that discarded it. The money went back, the booking stayed
     * confirmed, its slot stayed blocked, and nothing reported a failure because
     * from the modal's side nothing had failed.
     *
     * Here rather than in the callers for the reason `stop_plan` is here: there
     * is one place to get it right instead of four, and the refund and the
     * cancellation can be reported as one outcome.
     */
    cancel_booking: z.boolean().optional(),
    /*
     * Why the arrangement is over — REQUIRED whenever `stop_plan` or
     * `cancel_booking` is set, enforced by the refine below.
     *
     * One code for both toggles, because they are one decision: this arrangement
     * has ended. Two pickers would ask the same question twice of somebody who
     * already answered it.
     *
     * Not required for a plain refund. Returning money is not calling anything
     * off — the appointment may well still be happening — and the refund has its
     * own `reason` field for why the money went back.
     */
    cancel_reason: z.enum(STOP_REASONS).optional(),
  })
  .refine(
    body => !!(body.transaction_id || body.invoice_id || body.booking_id),
    { message: 'One of transaction_id, invoice_id or booking_id is required' }
  )
  /*
   * Conditional, not unconditional: a plain refund needs no cancellation reason,
   * and demanding one would block the commonest use of this route.
   */
  .refine(
    body => !(body.stop_plan || body.cancel_booking) || !!body.cancel_reason,
    { message: 'cancel_reason is required when stopping a plan or cancelling a booking' }
  );

/** Which HTTP status each refusal deserves. */
const STATUS_FOR: Record<string, number> = {
  NOT_FOUND: 404,
  NOT_REFUNDABLE: 409,
  // The request was valid; the server cannot safely act on it yet.
  ACCOUNT_UNRESOLVED: 409,
  // The state of the resource forbids it, and no retry of this request changes
  // that — this money did not come in through Stripe, so it cannot go back out
  // through Stripe.
  MISSING_REFERENCE: 409,
  BALANCE_INSUFFICIENT: 409,
  NOTHING_REMAINING: 409,
  // 409, the conventional code for "a conflicting request is already in
  // progress" — an in-flight refund is not the caller's mistake to correct, and
  // a retry after it settles is the right response.
  IN_FLIGHT: 409,
  EXCEEDS_REMAINING: 400,
  NOT_POSITIVE: 400,
  // The caller must choose. 409 rather than 400: nothing about the request is
  // malformed, the resource simply has more than one payment behind it.
  AMBIGUOUS_TARGET: 409,
  PROCESSOR_ERROR: 502,
};

export async function POST(request: NextRequest) {
  const correlationId = request.headers.get('x-correlation-id') || crypto.randomUUID();
  const requestLogger = logger.child({ correlationId });

  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const parsed = RefundSchema.safeParse(await request.json());
    if (!parsed.success) {
      return NextResponse.json(
        { success: false, error: 'Invalid request', details: parsed.error.errors },
        { status: 400 }
      );
    }

    const body = parsed.data;

    // userId comes from the session and is never taken from the body — it is
    // what scopes the lookup, so a caller cannot refund someone else's payment
    // by naming its id.
    const targets = await resolveRefundTargets({
      userId: user.id,
      transactionId: body.transaction_id,
      invoiceId: body.invoice_id,
      bookingId: body.booking_id,
    });

    if ('error' in targets) {
      return NextResponse.json(
        { success: false, error: targets.message, code: targets.error },
        { status: STATUS_FOR[targets.error] ?? 400 }
      );
    }

    const { transactionIds } = targets;

    /*
     * Several payments, and the caller has not said what they mean.
     *
     * Answered with the count rather than a guess, so the dialog can offer the
     * choice. The old resolver took the newest of them silently — which on a
     * twelve-period plan refunded one period and told the owner the booking was
     * refunded.
     */
    if (transactionIds.length > 1 && !body.scope) {
      return NextResponse.json(
        {
          success: false,
          code: 'AMBIGUOUS_TARGET',
          error:
            'More than one payment was collected against this. Choose one payment, or refund all of them.',
          payment_count: transactionIds.length,
        },
        { status: 409 }
      );
    }

    /*
     * Refund the lot.
     *
     * No amount: an arbitrary sum split across several payments has no honest
     * answer, and whichever split was chosen the client's card statement would
     * not match the intent.
     */
    if (body.scope === 'all' && transactionIds.length > 1) {
      if (body.amount) {
        return NextResponse.json(
          {
            success: false,
            code: 'NOT_POSITIVE',
            error:
              'A partial amount applies to a single payment. Refunding everything returns each payment in full.',
          },
          { status: 400 }
        );
      }

      const group = await refundGroup({
        userId: user.id,
        transactionIds,
        reason: body.reason,
        reasonNote: body.reason_note,
        source: 'app',
        initiatedBy: user.id,
        clientRequestId: body.client_request_id,
        /*
         * The whole-booking path was the one place `manual` was dropped, so a
         * business with no payment account left could record a refund for a
         * single payment and not for the booking its payments belong to — which
         * is the button the dashboard offers on a cancelled booking. `refund`
         * still refuses it per leg while an account is connected.
         */
        manual: body.manual,
      });

      /*
       * No `severity` here on purpose — see the single-payment path below.
       * PAYMENT_REFUNDED's classification lives in lib/audit/events.ts alone.
       */
      auditTrail
        .log({
          action: 'PAYMENT_REFUNDED',
          entityType: 'payment_transaction',
          entityId: transactionIds[0],
          userId: user.id,
          changes: {
            scope: 'all',
            requested: group.requested,
            succeeded: group.succeeded,
            refundedTotal: group.refundedTotal,
            currency: group.currency,
          },
          request,
        })
        .catch(err => requestLogger.error({ err }, 'Audit failed (non-blocking)'));

      /*
       * The booking, so it stops reading `paid` over money that went back.
       *
       * `propagate_refund_to_booking` is the authority for this and covers the
       * path no application code sees — a refund issued from the Stripe
       * dashboard. This computes the same value from the same rows, so once the
       * trigger is in place it is a no-op; until then it is the only thing
       * keeping a refund from this screen out of step with the booking.
       */
      await syncBookingsForTransactions(transactionIds, user.id);

      // Told once for the whole intent, not once per period — twelve emails for
      // one refunded plan is worse than none.
      if (body.notify_contact && group.refundedTotal > 0) {
        await notifyRefund({
          userId: user.id,
          transactionId: transactionIds[0],
          refundAmount: group.refundedTotal,
          currency: group.currency ?? '',
          /*
           * The code only. `reason_note` is the owner's own sentence and this is
           * the CLIENT's email — the same line every cancellation surface draws.
           */
          reason: body.reason,
          notifyContact: true,
        });
      }

      const planStop = body.stop_plan
        ? await stopPlanBehind(user.id, transactionIds[0], body.reason, requestLogger, body.cancel_reason)
        : null;

      /*
       * After the plan, and after the money.
       *
       * `cancelBooking` frees the slot by removing the calendar event and emails
       * the client, so it must not run before the refund has actually succeeded:
       * a client told their booking is cancelled while the money is still held is
       * worse than one told nothing yet.
       */
      const bookingCancel = body.cancel_booking
        ? await cancelBookingBehind(
            user.id,
            transactionIds[0],
            body.booking_id,
            body.reason,
            requestLogger,
            body.cancel_reason
          )
        : null;

      /*
       * A partial success is reported as a failure of the whole request.
       *
       * Stripe refunds are individually final, so seven of twelve cannot be
       * rolled back — but answering 200 would let the caller show "refunded"
       * over money still held. The legs say exactly what happened.
       */
      const complete = group.succeeded === group.requested;

      return NextResponse.json(
        {
          success: complete,
          data: { ...group, plan_stopped: planStop, booking_cancelled: bookingCancel },
          error: complete
            ? undefined
            : `${group.succeeded} of ${group.requested} payments were refunded.`,
        },
        { status: complete ? 200 : 409 }
      );
    }

    const transactionId = transactionIds[0];

    const result = await refund({
      userId: user.id,
      transactionId,
      amount: body.amount,
      reason: body.reason,
      manual: body.manual,
      source: 'app',
      initiatedBy: user.id,
      clientRequestId: body.client_request_id,
    });

    if (!result.ok) {
      requestLogger.warn(
        { userId: user.id, transactionId, code: result.code },
        'Refund refused'
      );
      return NextResponse.json(
        { success: false, error: result.message, code: result.code, remaining: result.remaining },
        { status: STATUS_FOR[result.code] ?? 400 }
      );
    }

    /*
     * Money leaving the business is about as material as this product gets, so
     * it is always audited — and never allowed to fail the request.
     *
     * `severity` is deliberately NOT passed. It used to be 'critical' here, and
     * AuditTrailService prefers the caller's value over the registration, so the
     * two could (and did) drift apart. A refund is a normal operation an owner
     * performs on their own client, and at 'critical' it was counted by the admin
     * health tile — which counts severity action-blind — and shown on the owner's
     * own /monitoring page as a security event needing immediate review. It is
     * registered 'warning' with the SOC2 flag in lib/audit/events.ts, which is now
     * the only place that decides, for both refund paths.
     */
    auditTrail
      .log({
        action: 'PAYMENT_REFUNDED',
        entityType: 'payment_transaction',
        entityId: transactionId,
        userId: user.id,
        changes: {
          refundId: result.refundId,
          processorRefundId: result.processorRefundId,
          amount: result.amount,
          currency: result.currency,
          replayed: result.replayed,
        },
        request,
      })
      .catch(err => requestLogger.error({ err }, 'Audit failed (non-blocking)'));

    // See the group path above: the trigger owns this, and this keeps the
    // booking correct until the trigger exists.
    await syncBookingsForTransactions([transactionId], user.id);

    // Awaited, not fired and forgotten: `notifyRefund` never throws, and the
    // owner pressing "notify the client" deserves the send to have been
    // attempted before the dialog reports success.
    await notifyRefund({
      userId: user.id,
      transactionId,
      refundAmount: result.amount,
      currency: result.currency,
      reason: body.reason,
      notifyContact: body.notify_contact,
      refundId: result.refundId,
    });

    /*
     * The plan, if asked — AFTER the refund, and only if it succeeded.
     *
     * A stopped plan over a failed refund is the worst pairing available: the
     * client keeps their money owed to them and stops being able to pay it.
     */
    const planStopped = body.stop_plan
      ? await stopPlanBehind(user.id, transactionId, body.reason, requestLogger, body.cancel_reason)
      : null;

    return NextResponse.json({ success: true, data: { ...result, plan_stopped: planStopped } });
  } catch (error) {
    requestLogger.error({ err: error }, 'Refund request failed');
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    );
  }
}


/**
 * Refunds a business has issued, most recent first.
 *
 * Reads the LEDGER rather than the derived columns on transactions, because
 * those answer a different question: they say how much of a SALE came back,
 * attributed to the sale's date. This says what left the business and when —
 * which is what a period report means by "refunds", and the only place the
 * reason, the source and the initiator survive.
 *
 * Failed and pending rows are included and labelled. A refund that did not go
 * through is a thing the owner needs to see: it is money they believe they
 * returned and did not.
 */
async function listRefunds(request: NextRequest, userId: string) {
  const params = new URL(request.url).searchParams;
  const from = params.get('from');
  const to = params.get('to');
  const forTransaction = params.get('transaction_id');
  const limit = Math.min(Number(params.get('limit')) || 100, 500);

  let query = supabaseServer
    .from('payment_refunds')
    .select(
      'id, transaction_id, invoice_id, amount, currency, status, reason, source, ' +
        'processor_refund_id, failure_code, failure_message, succeeded_at, created_at'
    )
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);

  // One payment's refund history — what the detail drawer asks for when the
  // owner wants to know why money went back, and how many times.
  if (forTransaction) query = query.eq('transaction_id', forTransaction);

  /*
   * Filtered on `succeeded_at` when a period is given, not `created_at`.
   *
   * A refund belongs to the period in which the money left, and those differ
   * whenever a refund was created near midnight or settled after a retry.
   * `created_at` is the fallback ordering because a pending row has no
   * `succeeded_at` yet.
   */
  if (from) query = query.gte('succeeded_at', from);
  if (to) query = query.lte('succeeded_at', to);

  const { data, error } = await query;

  if (error) {
    logger.error({ err: error, userId }, 'Could not read the refund ledger');
    return NextResponse.json(
      { success: false, error: 'Could not read refunds' },
      { status: 500 }
    );
  }

  /*
   * Typed here because the select list is built by concatenation, which defeats
   * PostgREST's compile-time column inference — it falls back to an error type
   * and every field access below fails to compile.
   */
  interface RefundRow {
    id: string;
    amount: number | string | null;
    currency: string | null;
    status: string;
  }

  const rows = (data ?? []) as unknown as RefundRow[];
  const succeeded = rows.filter(row => row.status === 'succeeded');

  // Per currency, never summed across. A total mixing ¥ and £ is worse than no
  // total at all.
  const totals: Record<string, number> = {};
  for (const row of succeeded) {
    const currency = (row.currency || 'unknown').toUpperCase();
    totals[currency] = Math.round(((totals[currency] ?? 0) + Number(row.amount || 0)) * 100) / 100;
  }

  return NextResponse.json({
    success: true,
    data: {
      refunds: rows,
      count: rows.length,
      succeeded_count: succeeded.length,
      totals_by_currency: Object.entries(totals).map(([currency, amount]) => ({ currency, amount })),
      // Said explicitly, so a page showing 500 rows does not read as "all of
      // them" when there are more.
      truncated: rows.length === limit,
    },
  });
}



/**
 * Stop the plan behind a payment, as part of the refund that just happened.
 *
 * One request, one intent. Asking the client to press refund and then find the
 * Stop button somewhere else is how a business ends up refunding a client and
 * charging them again the following month.
 *
 * Never throws: the money has already moved, and a refund must not be reported
 * as failed because the plan could not also be stopped. What happened is
 * returned so the dialog can say so.
 */
async function stopPlanBehind(
  userId: string,
  transactionId: string,
  reason: string | undefined,
  log: typeof logger,
  /** The countable half, so a plan stopped from the refund dialog records one too. */
  reasonCode?: StopReason
): Promise<{ stopped: boolean; cancelled_periods?: number; error?: string } | null> {
  try {
    const bookingId = await bookingBehind(userId, transactionId);
    if (!bookingId) return null;

    const { data: plan } = await supabaseServer
      .from('payment_plan_subscriptions')
      .select('id')
      .eq('user_id', userId)
      .eq('booking_id', bookingId)
      .in('status', ['active', 'past_due'])
      .maybeSingle();

    if (!plan) return null;

    if (!process.env.STRIPE_SECRET_KEY) {
      return { stopped: false, error: 'Payments are not configured.' };
    }

    const outcome = await cancelPlan({
      planId: plan.id,
      userId,
      stripe: new Stripe(process.env.STRIPE_SECRET_KEY),
      // The refund is already happening; asking cancelPlan to refund as well
      // would return the same money twice.
      refundCollected: false,
      reason,
      reasonCode,
    });

    if (!outcome.ok) {
      log.warn({ planId: plan.id, code: outcome.code }, 'Refunded, but the plan could not be stopped');
      return { stopped: false, error: outcome.message };
    }

    return { stopped: true, cancelled_periods: outcome.cancelledPeriods ?? 0 };
  } catch (err) {
    log.error({ err, transactionId }, 'Refunded, but stopping the plan threw');
    return { stopped: false, error: 'The plan could not be stopped.' };
  }
}

/**
 * The payment plan still billing this booking, if there is one.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * Refunding a plan payment does NOT stop the plan. The client gets their money
 * back and is charged again next period — and from the CRM booking there was no
 * way to stop it at all, because that path had no idea a plan existed. The
 * orders page grew a Stop button and the contact drawer did not, so the same
 * money behaved differently depending on where the owner opened it.
 *
 * Reported to the refund dialog instead, which every surface shares, so the
 * choice appears in all of them at once.
 *
 * `completed` and `cancelled` plans are deliberately absent: there is nothing
 * left to stop, and offering it would imply future charges that are not coming.
 */
async function livePlanFor(userId: string, bookingId: string | null) {
  if (!bookingId) return null;

  const { data } = await supabaseServer
    .from('payment_plan_subscriptions')
    .select('id, status, installment_count, periods_paid')
    .eq('user_id', userId)
    .eq('booking_id', bookingId)
    .in('status', ['active', 'past_due'])
    .maybeSingle();

  if (!data) return null;

  return {
    id: data.id,
    status: data.status,
    periods_remaining: Math.max(0, (data.installment_count ?? 0) - (data.periods_paid ?? 0)),
    // The whole arrangement, so a refund dialog opened from a booking can show
    // the same plan context the money drawer does — "2 of 3 collected" — rather
    // than only what is left to cancel.
    installment_count: data.installment_count ?? 0,
    periods_paid: data.periods_paid ?? 0,
  };
}

/**
 * The booking a payment belongs to.
 *
 * Directly, or through the invoice it settled. Which link exists depends on the
 * surface that sold it — a website sale writes `booking_id` on the transaction,
 * an invoice raised for a booking carries it on the invoice — and reading only
 * the first would hide a live payment plan from any refund started from the
 * invoices tab.
 */
/**
 * Cancel the booking this refund paid for, and free its slot.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY `cancelBooking` AND NOT AN UPDATE.
 *
 * Setting `status = 'cancelled'` here would mark the row and leave everything
 * else behind: the calendar event still holding the slot, unpaid invoices still
 * chasing, the client never told. `cancelBooking` is the one path that does all
 * of it, and every other surface that cancels already goes through it.
 *
 * FREEING THE SLOT IS THE POINT. Availability is computed from bookings that are
 * not cancelled, so the status change is what reopens the time — and
 * `cancelBooking` removes the external calendar event too, which is the half a
 * status change cannot do. A booking already in the past has no slot to free; it
 * is still cancelled, because the record should say what happened.
 *
 * REPORTED, NEVER THROWN. The refund has already succeeded and cannot be undone,
 * so a failure here must not turn a completed refund into a 500 — the caller is
 * told the money went back and the booking did not, which is the only honest
 * answer and the one the owner can act on.
 * ─────────────────────────────────────────────────────────────────────────────
 */
async function cancelBookingBehind(
  userId: string,
  transactionId: string | undefined,
  explicitBookingId: string | undefined,
  reason: string | undefined,
  log: typeof logger,
  /** The countable half, so this path is not the one hole in a mandatory rule. */
  reasonCode?: StopReason
): Promise<{ cancelled: boolean; booking_id?: string; error?: string } | null> {
  try {
    /*
     * The caller's own id first. The CRM drawer refunds by booking and sends it
     * directly; the money list and the payments tab send a transaction or an
     * invoice, and the booking has to be traced back from there.
     */
    const bookingId =
      explicitBookingId ?? (transactionId ? await bookingBehind(userId, transactionId) : null);

    if (!bookingId) {
      log.warn({ transactionId }, 'Refund asked to cancel a booking, but none could be resolved');
      return { cancelled: false, error: 'No booking found for this payment.' };
    }

    const { data, error } = await cancelBooking({
      bookingId,
      userId,
      reason,
      cancelReason: reasonCode ?? null,
      cancelNote: reason ?? null,
      // The owner pressed the toggle in the refund dialog.
      cancelledBy: 'owner',
      /*
       * No invitation to rebook. The client has just been refunded for this, and
       * "book again" under a refund reads as a business that would rather have
       * kept the money.
       */
      offerRebooking: false,
    });

    if (error || !data) {
      log.error({ err: error, bookingId }, 'Refunded, but the booking could not be cancelled');
      return { cancelled: false, booking_id: bookingId, error: error?.message };
    }

    log.info(
      { bookingId, calendarEventRemoved: data.calendarEventRemoved, clientNotified: data.clientNotified },
      'Booking cancelled alongside the refund'
    );
    return { cancelled: true, booking_id: bookingId };
  } catch (err) {
    log.error({ err }, 'Cancelling the booking after a refund threw');
    return {
      cancelled: false,
      error: err instanceof Error ? err.message : 'Could not cancel the booking.',
    };
  }
}

async function bookingBehind(userId: string, transactionId: string): Promise<string | null> {
  const { data } = await supabaseServer
    .from('payment_transactions')
    .select('booking_id, invoice_id')
    .eq('id', transactionId)
    .eq('user_id', userId)
    .maybeSingle();

  if (data?.booking_id) return data.booking_id;
  if (!data?.invoice_id) return null;

  const { data: invoice } = await supabaseServer
    .from('payment_invoices')
    .select('booking_id')
    .eq('id', data.invoice_id)
    .eq('user_id', userId)
    .maybeSingle();

  return invoice?.booking_id ?? null;
}

/**
 * What the UI needs to render an honest button: the real maximum, and the real
 * reason when there is none. Without this the client has to guess, which is why
 * the existing modal's cap can be bypassed by posting directly.
 */
export async function GET(request: NextRequest) {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
    }

    const params = new URL(request.url).searchParams;
    const transactionId = params.get('transaction_id');
    const invoiceId = params.get('invoice_id');
    const bookingId = params.get('booking_id');

    /*
     * The ledger itself.
     *
     * `payment_refunds` records the amount, the currency, the reason, who asked
     * for it, which surface it came from and when it succeeded — and NOTHING
     * read it. `idx_payment_refunds_user(user_id, created_at DESC)` was built
     * for exactly this listing and had no queries behind it, so "how much did I
     * refund this month, and why" was unanswerable from anywhere in the product.
     */
    if (params.get('list') === '1' || params.has('from') || params.has('to')) {
      return await listRefunds(request, user.id);
    }

    if (!transactionId && !invoiceId && !bookingId) {
      return NextResponse.json(
        { success: false, error: 'One of transaction_id, invoice_id or booking_id is required' },
        { status: 400 }
      );
    }

    /*
     * The same resolver the POST uses.
     *
     * Asking only for `transaction_id` meant the invoice list and the CRM
     * booking modal — which know an invoice or a booking, not a payment — could
     * not check anything, and opened a refund dialog that only discovered the
     * payment was unrefundable when the owner pressed the button.
     */
    const resolved = await resolveRefundTargets({
      userId: user.id,
      transactionId: transactionId ?? undefined,
      invoiceId: invoiceId ?? undefined,
      bookingId: bookingId ?? undefined,
    });

    if ('error' in resolved) {
      return NextResponse.json({
        success: true,
        data: { refundable: false, reason: resolved.error, detail: resolved.message, remaining: 0 },
      });
    }

    const verdicts = await Promise.all(
      resolved.transactionIds.map(id => getRefundability(user.id, id))
    );

    /*
     * ONE payment: its own answer, unchanged.
     *
     * SEVERAL: the aggregate, because the dialog was opened on a booking and
     * "how much can I get back" means all of it. Reporting only the newest
     * payment's remaining figure is what let a twelve-period plan offer a
     * one-period refund labelled as the whole booking.
     */
    if (verdicts.length === 1) {
      /*
       * The fee Stripe keeps, so the dialog can say what a refund costs.
       *
       * Stripe does not return the processing fee on a refund: returning ₪200
       * leaves the business ₪6.30 down. That is a fact worth knowing BEFORE
       * pressing the button, and nothing in the product has ever said it.
       */
      const { data: feeRow } = await supabaseServer
        .from('payment_transactions')
        .select('processor_fee, fee_currency')
        .eq('id', resolved.transactionIds[0])
        .eq('user_id', user.id)
        .maybeSingle();

      return NextResponse.json({
        success: true,
        data: {
          ...verdicts[0],
          payment_count: 1,
          // Null when the fee is not known yet, which the dialog treats as
          // "say nothing" rather than "there is no fee".
          processor_fee: feeRow?.processor_fee ?? null,
          fee_currency: feeRow?.fee_currency ?? null,
          plan: await livePlanFor(user.id, await bookingBehind(user.id, resolved.transactionIds[0])),
        },
      });
    }

    const refundable = verdicts.filter(v => v.refundable);
    const remaining = Math.round(refundable.reduce((sum, v) => sum + v.remaining, 0) * 100) / 100;

    const groupBooking = bookingId ?? (await bookingBehind(user.id, resolved.transactionIds[0]));

    return NextResponse.json({
      success: true,
      data: {
        plan: await livePlanFor(user.id, groupBooking),
        // Refundable if ANY of them is. A plan with one unresolved period is
        // still eleven-twelfths refundable, and refusing the lot over it would
        // strand the money the platform can return.
        refundable: refundable.length > 0,
        remaining,
        currency: refundable[0]?.currency ?? null,
        payment_count: resolved.transactionIds.length,
        // What is NOT refundable, and why — so a dialog offering "everything"
        // can say honestly that some of it will not come back.
        blocked_count: verdicts.length - refundable.length,
        reason: refundable.length === 0 ? verdicts[0]?.reason : undefined,
      },
    });
  } catch (error) {
    logger.error({ err: error }, 'Refundability check failed');
    return NextResponse.json({ success: false, error: 'Internal server error' }, { status: 500 });
  }
}
