// Connection point represents a field that can be connected
export interface ConnectionPoint {
  stepIndex: number;
  fieldIndex: number;
  fieldName: string;
  fieldType: string;
  isOutput: boolean;
  displayName?: string;
  description?: string;
  required?: boolean;
}

// Data transformation configuration
export interface DataTransform {
  id: string;
  type: 'map' | 'filter' | 'transform' | 'aggregate' | 'split' | 'combine';
  config: Record<string, any>;
  script?: string; // JavaScript transformation code
  description?: string;
}

// Connection between two fields (for advanced connection system)
export interface Connection {
  id: string;
  from: ConnectionPoint;
  to: ConnectionPoint;
  transform?: DataTransform;
  isActive: boolean;
  isAutoGenerated?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
  metadata?: {
    color?: string;
    label?: string;
    priority?: number;
  };
}

// Connection validation result
export interface ValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

// Connection suggestion for auto-connect
export interface ConnectionSuggestion {
  from: ConnectionPoint;
  to: ConnectionPoint;
  reason: string;
  confidence: number;
  autoConnect?: boolean;
}

// Field type compatibility definition
export interface FieldTypeCompatibility {
  [sourceType: string]: {
    compatible: string[];
    requiresTransform: string[];
    incompatible: string[];
  };
}

// Connection visualization properties
export interface ConnectionVisualization {
  path: string;
  strokeColor: string;
  strokeWidth: number;
  isHighlighted: boolean;
  isSelected: boolean;
  animationDelay?: number;
}

// Connection group for organizing related connections
export interface ConnectionGroup {
  id: string;
  name: string;
  description?: string;
  connections: string[]; // Connection IDs
  color?: string;
  isCollapsed?: boolean;
}

// Connection history for undo/redo
export interface ConnectionHistory {
  id: string;
  action: 'create' | 'update' | 'delete';
  connection: Connection;
  timestamp: Date;
  user?: string;
}

// Connection template for reusable patterns
export interface ConnectionTemplate {
  id: string;
  name: string;
  description: string;
  pattern: {
    sourceStepType: string;
    targetStepType: string;
    connections: Array<{
      fromField: string;
      toField: string;
      transform?: DataTransform;
    }>;
  };
  tags: string[];
}

// Connection metrics for analytics
export interface ConnectionMetrics {
  totalConnections: number;
  activeConnections: number;
  errorConnections: number;
  autoGeneratedConnections: number;
  manualConnections: number;
  connectionsWithTransforms: number;
  averageConnectionsPerStep: number;
  typeCompatibilityRate: number;
}

// Connection event for real-time updates
export interface ConnectionEvent {
  type: 'connection.created' | 'connection.updated' | 'connection.deleted' | 'connection.validated';
  connectionId: string;
  connection?: Connection;
  timestamp: Date;
  source: 'user' | 'system' | 'auto';
  metadata?: Record<string, any>;
}

// Field mapping for complex transformations
export interface FieldMapping {
  sourceFields: string[];
  targetField: string;
  mappingType: 'direct' | 'computed' | 'conditional' | 'aggregate';
  expression?: string;
  conditions?: Array<{
    condition: string;
    value: any;
  }>;
}

// Connection configuration options
export interface ConnectionConfig {
  enableAutoConnect: boolean;
  enableTypeValidation: boolean;
  enableCircularDependencyCheck: boolean;
  maxConnectionsPerField: number;
  defaultTransformType: DataTransform['type'];
  visualizationOptions: {
    showAnimations: boolean;
    showLabels: boolean;
    showTypeIcons: boolean;
    curveStyle: 'smooth' | 'straight' | 'stepped';
  };
}

// Connection state for the hook
export interface ConnectionState {
  connections: Connection[];
  selectedConnection: Connection | null;
  hoveredConnection: Connection | null;
  draggedField: ConnectionPoint | null;
  validationResults: ValidationResult | null;
  isValidating: boolean;
  config: ConnectionConfig;
}

// Connection operations for the hook
export interface ConnectionOperations {
  addConnection: (connection: Connection) => void;
  removeConnection: (connectionId: string) => void;
  updateConnection: (connectionId: string, updates: Partial<Connection>) => void;
  validateConnections: () => ValidationResult;
  autoConnect: () => Connection[];
  clearConnections: () => void;
  exportConnections: () => string;
  importConnections: (data: string) => void;
}

// Props for connection components
export interface ConnectionComponentProps {
  connections: Connection[];
  onConnectionChange?: (connections: Connection[]) => void;
  onConnectionSelect?: (connection: Connection | null) => void;
  onConnectionHover?: (connection: Connection | null) => void;
  config?: Partial<ConnectionConfig>;
  className?: string;
}

// Drag and drop interfaces
export interface DragData {
  type: 'field';
  connectionPoint: ConnectionPoint;
}

export interface DropResult {
  success: boolean;
  connection?: Connection;
  error?: string;
}

// Connection search and filter
export interface ConnectionFilter {
  stepIndex?: number;
  fieldType?: string;
  hasTransform?: boolean;
  isActive?: boolean;
  isAutoGenerated?: boolean;
  searchTerm?: string;
}

export interface ConnectionSearchResult {
  connections: Connection[];
  totalCount: number;
  hasMore: boolean;
}