// GENERATED by scripts/generate-test-account-cleanup-sql.ts. Never edit by hand.
// The version stamp the test-account cleanup database function returns. The
// delete route refuses before the storage step when the applied function
// returns another one (SA re-ruling R-6). The drift test pins it.

export const CLEANUP_FUNCTION_VERSION = 'e0c53390c6555ecf';
