/**
 * Generate `lib/geo/adminLabels.generated.ts` from `lib-address`.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THIS EXISTS
 *
 * A settings form has to know whether a country writes an administrative area
 * and what that area is CALLED — "state" in the US, "province" in Canada,
 * "prefecture" in Japan. Two of those three facts are in `lib-address/lite`,
 * which bundles every country for the browser in 52KB. The name is not: lite
 * carries no `state_name_type` or `zip_name_type`.
 *
 * Reading the full package in the browser is not an option. Its `exports` map
 * serves `entry-browser.mjs` there, which registers NO countries and expects
 * the app to register them — and the per-country files cannot be reached
 * either, because `./countries/*` is exported while `./countries` is not, so a
 * dynamic import cannot build its context.
 *
 * The names are static data about countries. They are extracted once, here, and
 * committed, so the browser needs no network call to know that the United
 * States has states. Before this, it asked a route — and a form that cannot
 * draw a field until a round trip succeeds is a form that sometimes does not
 * draw it.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * RUN IT when `lib-address` is upgraded:
 *
 *     npx tsx scripts/generate-address-labels.ts
 *
 * The output is checked in. Nothing reads `lib-address`'s per-country files at
 * runtime.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const SOURCE = join(process.cwd(), 'node_modules', 'lib-address', 'countries');
const TARGET = join(process.cwd(), 'lib', 'geo', 'adminLabels.generated.ts');

interface Entry {
  admin?: string;
  postal?: string;
}

const labels: Record<string, Entry> = {};

for (const file of readdirSync(SOURCE).sort()) {
  if (!file.endsWith('.json')) continue;

  const code = file.replace(/\.json$/, '');
  const data = JSON.parse(readFileSync(join(SOURCE, file), 'utf8')) as {
    state_name_type?: string;
    zip_name_type?: string;
  };

  const entry: Entry = {};
  if (data.state_name_type) entry.admin = data.state_name_type;
  if (data.zip_name_type) entry.postal = data.zip_name_type;

  // Countries carrying neither simply fall back at the call site.
  if (entry.admin || entry.postal) labels[code] = entry;
}

const withAdmin = Object.values(labels).filter(entry => entry.admin).length;

const body = `/**
 * What each country calls its administrative area and its postcode.
 *
 * GENERATED by \`scripts/generate-address-labels.ts\` from \`lib-address\`'s
 * per-country data. Do not edit by hand; re-run the script after upgrading it.
 *
 * It exists because \`lib-address/lite\` — the only build that works in a
 * browser — carries the SHAPE of an address but not these names, and the full
 * package cannot be read in a browser at all. See the script for the detail.
 *
 * ${Object.keys(labels).length} countries, ${withAdmin} of which have an administrative area.
 */

export interface AddressLabelNames {
  /** \`state\`, \`province\`, \`prefecture\`… Absent where a country has none. */
  admin?: string;
  /** \`zip\`, \`postal code\`, \`pin\`… */
  postal?: string;
}

export const ADDRESS_LABELS: Readonly<Record<string, AddressLabelNames>> = ${JSON.stringify(
  labels,
  null,
  2
)};
`;

writeFileSync(TARGET, body);

console.log(
  `Wrote ${TARGET.replace(process.cwd() + '/', '')}: ` +
    `${Object.keys(labels).length} countries, ${withAdmin} with an administrative area.`
);
