/**
 * NEW Deterministic Pipeline Test
 *
 * Tests the NEW deterministic pipeline architecture:
 * 1. IntentContract (Generic V1) - loaded from file (will be generated by LLM in future)
 * 2. CapabilityBinderV2 (Deterministic) → BoundIntentContract
 * 3. IntentToIRConverter (Deterministic) → ExecutionGraph (IR v4)
 * 4. ExecutionGraphCompiler (Deterministic) → PILOT DSL Steps
 *
 * This is the NEW pipeline that will replace the current LLM-based IR generation.
 */

import fs from 'fs'
import path from 'path'
import dotenv from 'dotenv'
import { CapabilityBinderV2 } from '../lib/agentkit/v6/capability-binding/CapabilityBinderV2'
import { IntentToIRConverter } from '../lib/agentkit/v6/compiler/IntentToIRConverter'
import { ExecutionGraphCompiler } from '../lib/agentkit/v6/compiler/ExecutionGraphCompiler'
import { PluginManagerV2 } from '../lib/server/plugin-manager-v2'
import type { IntentContract } from '../lib/agentkit/v6/semantic-plan/types/intent-schema-types'

// Load environment variables from .env.local
dotenv.config({ path: path.join(process.cwd(), '.env.local') })

async function main() {
  console.log('🚀 Testing NEW Deterministic Pipeline')
  console.log('=' .repeat(80))
  console.log('\nNOTE: This tests the NEW deterministic pipeline that will replace')
  console.log('the current LLM-based IR generation once validated.\n')
  console.log('=' .repeat(80))

  // =======================
  // PHASE 0: Setup
  // =======================
  console.log('\n📦 Phase 0: Setup')
  console.log('-'.repeat(80))

  const userId = '08456106-aa50-4810-b12c-7ca84102da31'

  // Initialize PluginManagerV2
  const pluginManager = await PluginManagerV2.getInstance()
  console.log(`✅ PluginManager initialized`)

  // Load existing IntentContract (Generic V1)
  // NOTE: In the future, this will be generated by an LLM from enhanced prompt
  const contractPath = path.join(process.cwd(), 'output', 'generic-intent-v1-contract.json')

  if (!fs.existsSync(contractPath)) {
    console.error(`❌ IntentContract not found: ${contractPath}`)
    console.error('Please generate an IntentContract first.')
    process.exit(1)
  }

  const intentContract: IntentContract = JSON.parse(fs.readFileSync(contractPath, 'utf-8'))

  console.log(`\n✅ Loaded IntentContract (Generic V1)`)
  console.log(`   Version: ${intentContract.version}`)
  console.log(`   Goal: ${intentContract.goal}`)
  console.log(`   Steps: ${intentContract.steps.length}`)
  console.log(`   Source: ${contractPath}`)

  // Create output directory
  const outputDir = path.join(process.cwd(), 'output', 'deterministic-pipeline')
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  // =======================
  // PHASE 1: Capability Binding (DETERMINISTIC)
  // =======================
  console.log('\n🔗 Phase 1: Capability Binding (CapabilityBinderV2 - DETERMINISTIC)')
  console.log('-'.repeat(80))

  const binder = new CapabilityBinderV2(pluginManager)

  console.log('Running deterministic capability binding...')
  console.log('(NO LLM - uses V6 plugin metadata for domain+capability matching)')

  const bindingStart = Date.now()
  const boundIntent = await binder.bind(intentContract, userId)
  const bindingTime = Date.now() - bindingStart

  console.log(`\n✅ Binding complete (${bindingTime}ms)`)
  console.log(`   Bound steps: ${boundIntent.steps.length}`)

  // Analyze binding results
  let successfulBindings = 0
  let failedBindings = 0
  const bindingDetails: any[] = []

  for (const step of boundIntent.steps) {
    if ('plugin_key' in step && step.plugin_key) {
      successfulBindings++
      const boundStep = step as any
      bindingDetails.push({
        step_id: step.id,
        kind: step.kind,
        plugin: boundStep.plugin_key,
        action: boundStep.action,
        confidence: boundStep.binding_confidence,
        method: boundStep.binding_method
      })
      console.log(`   ✅ ${step.id}: ${boundStep.plugin_key}.${boundStep.action} (confidence: ${boundStep.binding_confidence?.toFixed(2) || 'N/A'})`)
    } else {
      failedBindings++
      console.log(`   ⚠️  ${step.id}: No binding (kind: ${step.kind})`)
    }
  }

  console.log(`\n   Summary: ${successfulBindings} bound, ${failedBindings} unbound`)

  // Save Bound Intent Contract
  const boundIntentPath = path.join(outputDir, 'bound-intent-contract.json')
  fs.writeFileSync(boundIntentPath, JSON.stringify(boundIntent, null, 2))
  console.log(`   Saved: ${boundIntentPath}`)

  // =======================
  // PHASE 2: Intent → IR Conversion (DETERMINISTIC)
  // =======================
  console.log('\n🔄 Phase 2: Intent → IR Conversion (IntentToIRConverter - DETERMINISTIC)')
  console.log('-'.repeat(80))

  const converter = new IntentToIRConverter()

  console.log('Converting BoundIntentContract → ExecutionGraph (IR v4)...')
  console.log('(NO LLM - pure rule-based conversion)')

  const conversionStart = Date.now()
  const conversionResult = converter.convert(boundIntent)
  const conversionTime = Date.now() - conversionStart

  if (!conversionResult.success || !conversionResult.ir) {
    console.error('❌ Conversion failed!')
    console.error('Errors:', conversionResult.errors)
    process.exit(1)
  }

  const executionGraphIR = conversionResult.ir

  console.log(`\n✅ Conversion complete (${conversionTime}ms)`)
  console.log(`   IR Version: ${executionGraphIR.ir_version}`)
  console.log(`   Goal: ${executionGraphIR.goal}`)

  if (executionGraphIR.execution_graph) {
    console.log(`   Start Node: ${executionGraphIR.execution_graph.start}`)
    console.log(`   Total Nodes: ${Object.keys(executionGraphIR.execution_graph.nodes).length}`)

    // Node type breakdown
    const nodeTypes: Record<string, number> = {}
    for (const node of Object.values(executionGraphIR.execution_graph.nodes)) {
      nodeTypes[node.type] = (nodeTypes[node.type] || 0) + 1
    }

    console.log(`\n   Node Type Breakdown:`)
    for (const [type, count] of Object.entries(nodeTypes)) {
      console.log(`      - ${type}: ${count}`)
    }
  }

  if (conversionResult.warnings.length > 0) {
    console.log(`\n   ⚠️  Warnings (${conversionResult.warnings.length}):`)
    conversionResult.warnings.forEach(w => console.log(`      - ${w}`))
  }

  // Save ExecutionGraph (IR v4)
  const irPath = path.join(outputDir, 'execution-graph-ir-v4.json')
  fs.writeFileSync(irPath, JSON.stringify(executionGraphIR, null, 2))
  console.log(`\n   Saved: ${irPath}`)

  // =======================
  // PHASE 3: IR Compilation (DETERMINISTIC)
  // =======================
  console.log('\n⚙️  Phase 3: IR Compilation (ExecutionGraphCompiler - DETERMINISTIC)')
  console.log('-'.repeat(80))

  const compiler = new ExecutionGraphCompiler(pluginManager)

  console.log('Compiling ExecutionGraph → PILOT DSL Steps...')
  console.log('(NO LLM - compiles IR nodes to executable PILOT steps)')

  // NOTE: HardRequirements are optional - we're testing the pure deterministic pipeline
  // without requirements enforcement for now

  const compilationStart = Date.now()
  const compilationResult = await compiler.compile(executionGraphIR)
  const compilationTime = Date.now() - compilationStart

  if (!compilationResult.success || !compilationResult.workflow) {
    console.error('❌ Compilation failed!')
    console.error('Errors:', compilationResult.errors)
    if (compilationResult.errors) {
      compilationResult.errors.forEach((err: any) => {
        console.error(`   - ${err.message || err}`)
        if (err.context) {
          console.error(`     Context: ${JSON.stringify(err.context, null, 2)}`)
        }
      })
    }
    process.exit(1)
  }

  const pilotSteps = compilationResult.workflow

  console.log(`\n✅ Compilation complete (${compilationTime}ms)`)
  console.log(`   PILOT Steps: ${pilotSteps.length}`)

  // Step type breakdown
  const stepTypes: Record<string, number> = {}
  for (const step of pilotSteps) {
    stepTypes[step.type] = (stepTypes[step.type] || 0) + 1
  }

  console.log(`\n   PILOT Step Type Breakdown:`)
  for (const [type, count] of Object.entries(stepTypes)) {
    console.log(`      - ${type}: ${count}`)
  }

  // Save PILOT DSL Steps
  const pilotPath = path.join(outputDir, 'pilot-dsl-steps.json')
  fs.writeFileSync(pilotPath, JSON.stringify(pilotSteps, null, 2))
  console.log(`\n   Saved: ${pilotPath}`)

  // =======================
  // PHASE 4: Final Summary
  // =======================
  console.log('\n✅ Phase 4: Pipeline Summary')
  console.log('=' .repeat(80))

  console.log('\n🎉 NEW DETERMINISTIC PIPELINE TEST SUCCESSFUL!\n')

  console.log('Pipeline Flow (All Deterministic After Phase 1):')
  console.log(`  1. ✅ IntentContract (Generic V1) - ${intentContract.steps.length} steps`)
  console.log(`  2. ✅ CapabilityBinderV2 → BoundIntent (${successfulBindings} bindings, ${bindingTime}ms)`)
  console.log(`  3. ✅ IntentToIRConverter → ExecutionGraph (${executionGraphIR.execution_graph ? Object.keys(executionGraphIR.execution_graph.nodes).length : 0} nodes, ${conversionTime}ms)`)
  console.log(`  4. ✅ ExecutionGraphCompiler → PILOT DSL (${pilotSteps.length} steps, ${compilationTime}ms)`)

  const totalTime = bindingTime + conversionTime + compilationTime

  console.log('\n📊 Performance Stats:')
  console.log(`   Total Pipeline Time:  ${totalTime}ms`)
  console.log(`   - Binding:            ${bindingTime}ms (${((bindingTime / totalTime) * 100).toFixed(1)}%)`)
  console.log(`   - IR Conversion:      ${conversionTime}ms (${((conversionTime / totalTime) * 100).toFixed(1)}%)`)
  console.log(`   - IR Compilation:     ${compilationTime}ms (${((compilationTime / totalTime) * 100).toFixed(1)}%)`)

  console.log('\n📊 Pipeline Stats:')
  console.log(`   Intent Steps:         ${intentContract.steps.length}`)
  console.log(`   Successful Bindings:  ${successfulBindings}`)
  console.log(`   Failed Bindings:      ${failedBindings}`)
  console.log(`   IR Nodes:             ${executionGraphIR.execution_graph ? Object.keys(executionGraphIR.execution_graph.nodes).length : 0}`)
  console.log(`   PILOT Steps:          ${pilotSteps.length}`)
  console.log(`   Conversion Warnings:  ${conversionResult.warnings.length}`)

  console.log('\n📁 Output Files:')
  console.log(`   - ${boundIntentPath}`)
  console.log(`   - ${irPath}`)
  console.log(`   - ${pilotPath}`)

  console.log('\n✨ Key Achievement:')
  console.log('   🎯 Complete deterministic pipeline from IntentContract → PILOT DSL')
  console.log('   🎯 NO LLM calls after IntentContract generation')
  console.log('   🎯 All binding/conversion/compilation is rule-based')
  console.log('   🎯 Fast execution (<100ms typical for deterministic phases)')

  console.log('\n' + '=' .repeat(80))
  console.log('✅ NEW DETERMINISTIC PIPELINE VALIDATED')
  console.log('=' .repeat(80))
  console.log('\n📝 Next Steps:')
  console.log('   1. ✅ Review output files for correctness')
  console.log('   2. Test PILOT DSL execution')
  console.log('   3. Test with more complex workflows')
  console.log('   4. Integrate into V6PipelineOrchestrator')
  console.log('   5. Add IntentContract LLM generation')
  console.log('   6. Replace production LLM-based IR generation\n')
}

main().catch((err) => {
  console.error('\n❌ Pipeline test failed:', err)
  console.error('\nStack trace:', err.stack)
  process.exit(1)
})
