#!/usr/bin/env bash
#
# Typecheck gate for the Business OS chat stack.
#
# WHY THIS EXISTS
#
# `npx tsc --noEmit -p tsconfig.json` is unusable as a gate here, for two
# independent reasons, and BOTH of them silently produced a passing result:
#
#   1. It runs out of V8 heap and dies mid-check. A crashed tsc prints a stack
#      trace, not diagnostics — so grepping its output for your filenames finds
#      nothing, which looks exactly like success. An undefined `CATALOG` shipped
#      to a user this way.
#
#   2. The repo carries ~4,100 pre-existing errors (V6 tests, website pages).
#      Even when tsc completes, "did it exit non-zero" tells you nothing about
#      the code you just wrote.
#
# So: give tsc enough memory to finish, then compare errors in THIS stack's
# files against a recorded baseline. Anything new fails.
#
# Usage:
#   scripts/typecheck-business-chat.sh            # check
#   scripts/typecheck-business-chat.sh --baseline # re-record after fixing some
#
# HOW TO READ THE RESULT — this bit matters.
#
# Do NOT judge success by the exit code of a pipeline. `./this-script | tail`
# reports TAIL's status, not the script's, so a script that dies with a syntax
# error or a crashed tsc comes back 0 and looks like a pass. That happened: an
# edit to this file while it was running corrupted it mid-execution (bash reads
# scripts by byte offset), it exited 2, and the piped invocation reported 0.
#
# Either use `set -o pipefail`, or — more robustly — require one of the two
# verdict lines below to appear:
#
#     No new type errors in the Business OS chat stack.
#     NEW type errors:
#
# If NEITHER is present, the gate did not finish and the result is unknown.
# Absence of a verdict is a failure, never a pass.
#
# And do not edit this file while it is running.
#
set -uo pipefail

cd "$(dirname "$0")/.."

# Compared on file + line + error CODE, never the message text. TypeScript prints
# union members in a non-deterministic order, so an unchanged error can render as
# 'MutateResult | ForEachResult' one run and 'ForEachResult | MutateResult' the
# next — which a message-wise comparison reports as three new errors that do not
# exist. A gate that cries wolf gets ignored, which is how the last one failed.

# Files this work owns. Extend deliberately.
# Widened to the whole insight tree when automations work began: the kernel, the
# detectors and the automation manager are now in scope, and a gate that does not
# cover the files being edited is not a gate.
SCOPE='^(lib/business-os/(bizql|catalog|insight)|app/api/business-os/(chat-v4|insights|automations|saved-plans)|app/api/admin/chat-usage|app/api/business-os/usage|components/business-os/UsageCard|components/business-os/insight/|lib/analytics/aiAnalytics|lib/utils/analyticsHelpers|scripts/chat-usage-report|app/api/cron/insight-|components/business-os/ChatCommandPanel|tests/business-os-chat|scripts/bizql|scripts/generate-business-os-plugin|scripts/business-os-plugin-e2e|lib/server/business-os-plugin-executor)'

# `it(...)` in test files trips a repo-wide jest/@types clash that has nothing to
# do with this code — it fires identically in the V6 tests. Excluded so the
# signal is not buried; remove this once the repo's jest types are sorted out.
NOISE='error TS2345: Argument of type .\(\) => (Promise<void>|void). is not assignable to parameter of type .\(\) => boolean.'

BASELINE="scripts/.typecheck-business-chat.baseline"
CURRENT="$(mktemp)"
trap 'rm -f "$CURRENT"' EXIT

echo "Typechecking (this takes a few minutes) ..."

# 8GB: the default heap dies partway through this project.
NODE_OPTIONS="--max-old-space-size=8192" npx tsc --noEmit -p tsconfig.json 2>&1 \
  | grep -aE 'error TS' \
  | grep -aE "$SCOPE" \
  | grep -avE "$NOISE" \
  | sed -E 's/\(([0-9]+),[0-9]+\): (error TS[0-9]+).*/(\1): \2/' \
  | sort -u > "$CURRENT"

# A crashed tsc emits a stack trace and zero diagnostics, which is
# indistinguishable from a clean run by line count alone. Prove it actually ran.
if ! NODE_OPTIONS="--max-old-space-size=8192" npx tsc --version > /dev/null 2>&1; then
  echo "tsc could not run at all." >&2
  exit 2
fi

if [ "${1:-}" = "--baseline" ]; then
  cp "$CURRENT" "$BASELINE"
  echo "Baseline recorded: $(wc -l < "$BASELINE" | tr -d ' ') known error(s)."
  exit 0
fi

if [ ! -f "$BASELINE" ]; then
  echo "No baseline. Run with --baseline first." >&2
  exit 2
fi

NEW="$(comm -13 "$BASELINE" "$CURRENT")"
FIXED="$(comm -23 "$BASELINE" "$CURRENT")"

if [ -n "$FIXED" ]; then
  echo "Fixed since the baseline (re-record with --baseline):"
  echo "$FIXED" | sed 's/^/  - /'
  echo
fi

if [ -n "$NEW" ]; then
  echo "NEW type errors:"
  echo "$NEW" | sed 's/^/  ✗ /'
  exit 1
fi

echo "No new type errors in the Business OS chat stack."
