/**
 * What each country calls its administrative area and its postcode.
 *
 * GENERATED by `scripts/generate-address-labels.ts` from `lib-address`'s
 * per-country data. Do not edit by hand; re-run the script after upgrading it.
 *
 * It exists because `lib-address/lite` — the only build that works in a
 * browser — carries the SHAPE of an address but not these names, and the full
 * package cannot be read in a browser at all. See the script for the detail.
 *
 * 40 countries, 38 of which have an administrative area.
 */

export interface AddressLabelNames {
  /** `state`, `province`, `prefecture`… Absent where a country has none. */
  admin?: string;
  /** `zip`, `postal code`, `pin`… */
  postal?: string;
}

export const ADDRESS_LABELS: Readonly<Record<string, AddressLabelNames>> = {
  "AE": {
    "admin": "emirate"
  },
  "AS": {
    "admin": "state",
    "postal": "zip"
  },
  "AU": {
    "admin": "state"
  },
  "BB": {
    "admin": "parish"
  },
  "BR": {
    "admin": "state"
  },
  "BS": {
    "admin": "island"
  },
  "CO": {
    "admin": "department"
  },
  "CV": {
    "admin": "island"
  },
  "FM": {
    "admin": "state",
    "postal": "zip"
  },
  "FR": {
    "admin": "region"
  },
  "GU": {
    "postal": "zip"
  },
  "HK": {
    "admin": "area"
  },
  "HN": {
    "admin": "department"
  },
  "IE": {
    "admin": "county",
    "postal": "eircode"
  },
  "IN": {
    "admin": "state",
    "postal": "pin"
  },
  "JM": {
    "admin": "parish"
  },
  "JP": {
    "admin": "prefecture"
  },
  "KI": {
    "admin": "island"
  },
  "KN": {
    "admin": "island"
  },
  "KR": {
    "admin": "do_si"
  },
  "KY": {
    "admin": "island"
  },
  "MH": {
    "admin": "state",
    "postal": "zip"
  },
  "MP": {
    "admin": "state",
    "postal": "zip"
  },
  "MX": {
    "admin": "state"
  },
  "MY": {
    "admin": "state"
  },
  "NG": {
    "admin": "state"
  },
  "NI": {
    "admin": "department"
  },
  "NR": {
    "admin": "district"
  },
  "PF": {
    "admin": "island"
  },
  "PR": {
    "postal": "zip"
  },
  "PW": {
    "admin": "state",
    "postal": "zip"
  },
  "RU": {
    "admin": "oblast"
  },
  "SC": {
    "admin": "island"
  },
  "TV": {
    "admin": "island"
  },
  "TW": {
    "admin": "county"
  },
  "UA": {
    "admin": "oblast"
  },
  "UM": {
    "admin": "state",
    "postal": "zip"
  },
  "US": {
    "admin": "state",
    "postal": "zip"
  },
  "VE": {
    "admin": "state"
  },
  "VI": {
    "admin": "state",
    "postal": "zip"
  }
};
