/**
 * Every button the platform generates has somewhere real to go.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE FAILURE THIS CLOSES
 *
 * Sections are generated by four different producers — the website generator,
 * the landing-page builder, the block recipes and the onboarding build — and
 * each one writes its buttons' destinations as literal strings: `#services`,
 * `#booking`, `#contact`. Nothing checked those strings against the sections
 * the page ended up with, and nothing could: the table mapping a section to its
 * anchor lived inside the renderer, a client module no generator can import.
 * That table is now `./sectionAnchors`, shared by both halves.
 *
 * A fragment naming no element is the quietest failure a page can have. The
 * browser does not navigate, does not scroll and does not report anything — the
 * visitor presses "Book now" and the page sits there. It survives every test
 * that renders a page and looks at it, because the button IS there and looks
 * right.
 *
 * Three ways a destination goes dead, all of them seen in the live data:
 *
 *   1. A literal fallback nobody checked. The templated header's wordmark was
 *      `href="#"`, a fragment naming nothing, on every generated page.
 *   2. An anchor for a section this page does not have. A generator that writes
 *      `#booking` for a bookable service writes it from the SERVICE, while
 *      whether a `booking_widget` section exists is decided elsewhere.
 *   3. An anchor for a section the owner switched off. The renderer drops a
 *      disabled block before it stamps any ids, so every link to it dies at
 *      that moment, in content nobody edited.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHERE THIS RUNS, AND WHY THERE
 *
 * In the renderer, over the blocks it is about to draw — not in the generators.
 * Three reasons, and the third is the one that matters:
 *
 *   • It covers every surface at once. The published site, the editor's
 *     preview, the landing preview and the smart link all render through
 *     `WebsiteBlocks`.
 *   • It covers every page ALREADY STORED, without a migration.
 *   • The answer depends on facts the generators do not have. Whether a section
 *     is enabled, whether a service still exists, which sections survived the
 *     owner's editing — all of that is settled at render. A link checked at
 *     generation is checked against a page that no longer exists.
 *
 * Nothing here is stored. The stored content keeps the destination its
 * generator chose; this decides what the page does with it today.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * @module lib/website-builder/linkIntegrity
 */

import { pageAnchors } from './sectionAnchors';

/** The shape this works over: the stored block, whatever else it carries. */
interface BlockLike {
  block_type: string;
  content?: Record<string, unknown> | null;
  enabled?: boolean | null;
}

/**
 * Where a dead link is sent instead, in order of preference.
 *
 * A button is a conversion control, so the repair aims at the sections that
 * convert before the ones that merely inform. `booking` first because a page
 * that has it is a page built to take bookings; `services` and `pricing` next,
 * because that is where someone who pressed a dead "book now" was trying to
 * get; `contact` last, as the universal ask.
 */
const REPAIR_ORDER = ['booking', 'services', 'pricing', 'contact', 'about'] as const;

/** The keys a destination hides under, across four generators' vocabularies. */
const LINK_KEYS = ['cta_link', 'button_link', 'buttonLink', 'cta_url', 'link', 'href'] as const;

/** Arrays of `{ label, anchor }`-ish items: menus, footer columns. */
const MENU_KEYS = ['menu_items', 'links', 'nav_items', 'footer_links'] as const;

/** A fragment that names nothing at all, whatever the generator meant by it. */
function isEmptyFragment(value: string): boolean {
  const trimmed = value.trim();
  return trimmed === '' || trimmed === '#' || trimmed === '#!';
}

/**
 * Is this destination reachable on a page with these anchors?
 *
 * Only fragments are judged. A path or an absolute URL is somebody's decision
 * about another surface and this module has no standing to overrule it — the
 * one thing it can prove is whether a `#section` exists here.
 */
function fragmentIsDead(value: string, anchors: Set<string>): boolean {
  if (isEmptyFragment(value)) return true;
  if (!value.startsWith('#')) return false;
  return !anchors.has(value.slice(1));
}

/** The best destination this page can actually offer, or null if it has none. */
function repairTarget(anchors: Set<string>): string | null {
  for (const anchor of REPAIR_ORDER) {
    if (anchors.has(anchor)) return `#${anchor}`;
  }
  return null;
}

export interface LinkRepair {
  blockType: string;
  field: string;
  from: string;
  to: string | null;
}

/**
 * The same blocks, with every dead destination repaired or removed.
 *
 * REMOVED, not left empty, when the page has nowhere to offer: each converting
 * section resolves its own control when it has no link — the hero, the CTA and
 * the header all call `resolveBookingAction`, which opens the booking dialog
 * where there is one. So dropping a dead `cta_link` is an upgrade, not a loss:
 * the button stops scrolling nowhere and starts doing the thing it says.
 *
 * A dead MENU item is dropped outright. A menu is a list of places on this
 * page, and an entry pointing at a section that is not here has nothing to
 * become — repairing it to a different section would silently rename what the
 * owner wrote.
 *
 * Pure, and returns the same array when nothing needed fixing, so a caller can
 * memoise on identity.
 */
export function repairBlockLinks<T extends BlockLike>(
  blocks: T[]
): { blocks: T[]; repairs: LinkRepair[] } {
  const anchors = pageAnchors(blocks);
  const target = repairTarget(anchors);
  const repairs: LinkRepair[] = [];

  const repaired = blocks.map(block => {
    const content = block.content;
    if (!content) return block;

    let next: Record<string, unknown> | null = null;
    const edit = () => (next ??= { ...content });

    for (const key of LINK_KEYS) {
      const value = content[key];
      if (typeof value !== 'string' || !fragmentIsDead(value, anchors)) continue;

      repairs.push({ blockType: block.block_type, field: key, from: value, to: target });
      const draft = edit();
      if (target) draft[key] = target;
      else delete draft[key];
    }

    /*
     * The header's own button, which is an object rather than a string. Its
     * TEXT stays: the owner wrote "Book Now" and it is still a booking button,
     * it simply stops promising a place that is not there.
     */
    const button = content.cta_button as { link?: unknown; text?: unknown } | undefined;
    if (button && typeof button.link === 'string' && fragmentIsDead(button.link, anchors)) {
      repairs.push({ blockType: block.block_type, field: 'cta_button.link', from: button.link, to: target });
      const draft = edit();
      draft.cta_button = target ? { ...button, link: target } : { ...button, link: undefined };
    }

    for (const key of MENU_KEYS) {
      const items = content[key];
      if (!Array.isArray(items)) continue;

      const kept = items.filter(raw => {
        const item = raw as { anchor?: unknown; link?: unknown; href?: unknown } | null;
        const to = item?.anchor ?? item?.link ?? item?.href;
        // An item with no destination at all is somebody else's business —
        // a heading in a footer column, say. Only a stated one is judged.
        if (typeof to !== 'string') return true;
        if (!fragmentIsDead(to, anchors)) return true;

        repairs.push({ blockType: block.block_type, field: key, from: to, to: null });
        return false;
      });

      if (kept.length !== items.length) edit()[key] = kept;
    }

    return next ? ({ ...block, content: next } as T) : block;
  });

  return { blocks: repairs.length > 0 ? repaired : blocks, repairs };
}
