-- =====================================================
-- Add status column to scheduling_services
-- Supports draft services generated by AI Business Architect
-- =====================================================

-- Create enum for service status
DO $$ BEGIN
  CREATE TYPE service_status AS ENUM ('draft', 'active', 'inactive');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Add status column (default to 'active' for backward compatibility)
ALTER TABLE scheduling_services
  ADD COLUMN IF NOT EXISTS status service_status NOT NULL DEFAULT 'active';

-- Add source column to track how service was created
ALTER TABLE scheduling_services
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual';
-- Values: 'manual', 'ai_generated', 'template', 'imported'

-- Add ai_suggestions column to store AI-generated metadata
-- This helps preserve the AI's reasoning for the service configuration
ALTER TABLE scheduling_services
  ADD COLUMN IF NOT EXISTS ai_suggestions JSONB;
-- Example: { "reasoning": "Based on your bio mentioning therapy sessions...", "confidence": 0.85 }

-- Migrate existing is_active to new status column
-- This is safe because we're adding status with default 'active'
UPDATE scheduling_services
SET status = CASE
  WHEN is_active = false THEN 'inactive'::service_status
  ELSE 'active'::service_status
END
WHERE status IS NULL OR status = 'active';

-- Index for filtering by status
CREATE INDEX IF NOT EXISTS idx_scheduling_services_status ON scheduling_services(status);
CREATE INDEX IF NOT EXISTS idx_scheduling_services_source ON scheduling_services(source);

-- Comment
COMMENT ON COLUMN scheduling_services.status IS 'Service status: draft (AI-generated, awaiting review), active (bookable), inactive (hidden)';
COMMENT ON COLUMN scheduling_services.source IS 'How service was created: manual, ai_generated, template, imported';
COMMENT ON COLUMN scheduling_services.ai_suggestions IS 'AI metadata including reasoning and confidence for generated services';
