-- Seed Demo Data for Insight System (Hebrew)
-- This creates sample insights and autonomous work entries for testing the MyDay insight cards
--
-- IMPORTANT: Insights are stored with localized content directly in the database.
-- The title/description should be generated by the AI in the user's language when the insight is created.
-- This seed script uses Hebrew as the demo language.
--
-- USAGE:
-- 1. Get your user_id from the profiles or auth.users table
-- 2. Replace '{{USER_ID}}' with your actual user_id below
-- 3. Run this migration
--
-- Tables populated:
-- - insights: Active insights shown in InsightAdvisorCard
-- - kernel_executions: Completed autonomous work
-- - kernel_action_log: Feed entries for "what I've done for you"

-- ============================================================================
-- CONFIGURATION: Set your user_id here
-- ============================================================================
DO $$
DECLARE
  v_user_id UUID;
  v_insight_id_1 UUID;
  v_insight_id_2 UUID;
  v_insight_id_3 UUID;
  v_execution_id_1 UUID;
  v_execution_id_2 UUID;
  v_execution_id_3 UUID;
BEGIN
  -- Get the first user from profiles (you can change this query to target a specific user)
  SELECT user_id INTO v_user_id FROM business_profiles LIMIT 1;

  IF v_user_id IS NULL THEN
    RAISE NOTICE 'No user found in business_profiles. Please create a business profile first.';
    RETURN;
  END IF;

  RAISE NOTICE 'Seeding insight demo data for user: %', v_user_id;

  -- ============================================================================
  -- Clean up existing demo data (optional - remove if you want to keep old data)
  -- ============================================================================
  DELETE FROM kernel_action_log WHERE user_id = v_user_id;
  DELETE FROM kernel_executions WHERE user_id = v_user_id;
  DELETE FROM owner_insight_history WHERE user_id = v_user_id;
  DELETE FROM insights WHERE user_id = v_user_id;

  RAISE NOTICE 'Cleaned up existing insight data';

  -- ============================================================================
  -- INSERT INSIGHTS (Active issues to show in InsightAdvisorCard)
  -- All content is in Hebrew - the user's language
  -- ============================================================================

  -- Insight 1: Cash Flow - Overdue Invoices (High priority)
  v_insight_id_1 := gen_random_uuid();
  INSERT INTO insights (
    id,
    user_id,
    detector_id,
    category,
    severity,
    title,
    description,
    recommendation,
    metric_key,
    current_value,
    baseline_value,
    threshold_value,
    percent_change,
    direction,
    affected_entity_type,
    affected_count,
    estimated_impact_usd,
    impact_direction,
    impact_period,
    paired_process_id,
    process_parameters,
    eligible_for_automation,
    priority_score,
    status,
    surface_count,
    detected_at,
    created_at
  ) VALUES (
    v_insight_id_1,
    v_user_id,
    'cash_ar_overdue',
    'cash_flow',
    'high',
    -- Hebrew: "$2,840 is sitting unpaid across 7 invoices"
    '₪10,360 יושב ללא תשלום ב-7 חשבוניות',
    -- Hebrew: "The oldest is 3 weeks past due — about 12% of this month's income still waiting to land. I can send each client a warm, personal reminder right now."
    'הוותיקה ביותר ב-3 שבועות איחור — בערך 12% מההכנסה של החודש עדיין מחכה. אני יכול לשלוח לכל לקוח תזכורת חמה ואישית עכשיו.',
    -- Hebrew: "Send payment reminders to clients with overdue invoices. This could help recover up to $2,840."
    'שלח תזכורות תשלום ללקוחות עם חשבוניות באיחור. זה יכול לעזור לשחזר עד ₪10,360.',
    'ar_overdue_total',
    2840.00,
    500.00,
    1000.00,
    468.00,
    'above',
    'invoice',
    7,
    2840.00,
    'loss',
    'monthly',
    'chase_overdue_invoices',
    '{"days_threshold": 7, "reminder_tone": "friendly"}'::jsonb,
    true,
    85.00,
    'new',
    0,
    now() - interval '2 hours',
    now() - interval '2 hours'
  );

  RAISE NOTICE 'Created insight 1 (cash_ar_overdue): %', v_insight_id_1;

  -- Insight 2: Sales - Stalled Enquiries (Medium priority)
  v_insight_id_2 := gen_random_uuid();
  INSERT INTO insights (
    id,
    user_id,
    detector_id,
    category,
    severity,
    title,
    description,
    recommendation,
    metric_key,
    current_value,
    baseline_value,
    threshold_value,
    percent_change,
    direction,
    affected_entity_type,
    affected_count,
    estimated_impact_usd,
    impact_direction,
    impact_period,
    paired_process_id,
    process_parameters,
    eligible_for_automation,
    priority_score,
    status,
    surface_count,
    detected_at,
    created_at
  ) VALUES (
    v_insight_id_2,
    v_user_id,
    'sales_stalled',
    'sales',
    'medium',
    -- Hebrew: "4 enquiries are going cold"
    '4 פניות מתקררות',
    -- Hebrew: "These potential clients haven't heard back in over 48 hours. A quick follow-up now could save these leads."
    'הלקוחות הפוטנציאליים האלה לא קיבלו מענה מעל 48 שעות. מעקב מהיר עכשיו יכול להציל את הלידים האלה.',
    -- Hebrew: "Follow up with these leads to maintain momentum. Quick responses can significantly improve conversion rates."
    'עקוב אחרי הלידים האלה כדי לשמור על המומנטום. תגובות מהירות יכולות לשפר משמעותית את שיעורי ההמרה.',
    'leads_awaiting_reply',
    4.00,
    1.00,
    2.00,
    300.00,
    'above',
    'contact',
    4,
    1200.00,
    'opportunity',
    'weekly',
    'send_followup_nudge',
    '{"message_tone": "warm", "include_availability": true}'::jsonb,
    true,
    72.00,
    'new',
    0,
    now() - interval '4 hours',
    now() - interval '4 hours'
  );

  RAISE NOTICE 'Created insight 2 (sales_stalled): %', v_insight_id_2;

  -- Insight 3: Operations - Low Calendar Utilization (Low priority)
  v_insight_id_3 := gen_random_uuid();
  INSERT INTO insights (
    id,
    user_id,
    detector_id,
    category,
    severity,
    title,
    description,
    recommendation,
    metric_key,
    current_value,
    baseline_value,
    threshold_value,
    percent_change,
    direction,
    affected_entity_type,
    affected_count,
    estimated_impact_usd,
    impact_direction,
    impact_period,
    paired_process_id,
    process_parameters,
    eligible_for_automation,
    priority_score,
    status,
    surface_count,
    detected_at,
    created_at
  ) VALUES (
    v_insight_id_3,
    v_user_id,
    'ops_utilization_low',
    'operations',
    'low',
    -- Hebrew: "Your calendar is only 35% filled this week"
    'היומן שלך מלא רק ב-35% השבוע',
    -- Hebrew: "You have approximately 18 hours of available slots this week. Past clients who went quiet might book if nudged."
    'יש לך בערך 18 שעות פנויות השבוע. לקוחות עבר ששתקו אולי יזמינו אם תדחף אותם קצת.',
    -- Hebrew: "Consider promoting available time slots or running a special offer to fill your calendar."
    'שקול לקדם משבצות זמן פנויות או להריץ מבצע מיוחד כדי למלא את היומן שלך.',
    'calendar_utilization',
    35.00,
    65.00,
    50.00,
    -46.15,
    'below',
    'booking_slot',
    18,
    900.00,
    'opportunity',
    'weekly',
    'promote_availability',
    '{"target_audience": "past_clients", "offer_discount": false}'::jsonb,
    true,
    55.00,
    'new',
    0,
    now() - interval '6 hours',
    now() - interval '6 hours'
  );

  RAISE NOTICE 'Created insight 3 (ops_utilization_low): %', v_insight_id_3;

  -- ============================================================================
  -- INSERT KERNEL EXECUTIONS (Completed autonomous work)
  -- ============================================================================

  -- Execution 1: Chased overdue invoices
  v_execution_id_1 := gen_random_uuid();
  INSERT INTO kernel_executions (
    id,
    user_id,
    process_id,
    triggered_by,
    insight_id,
    parameters,
    status,
    items_processed,
    items_succeeded,
    items_failed,
    value_impact,
    summary,
    created_at,
    started_at,
    completed_at
  ) VALUES (
    v_execution_id_1,
    v_user_id,
    'chase_overdue_invoices',
    'automation',
    NULL,
    '{"days_threshold": 7}'::jsonb,
    'completed',
    5,
    2,
    0,
    680.00,
    -- Hebrew: "Chased 5 overdue invoices — 2 have paid ($680 in)"
    'רדפתי אחרי 5 חשבוניות באיחור — 2 שילמו (₪2,480 נכנסו)',
    now() - interval '6 hours',
    now() - interval '6 hours',
    now() - interval '5 hours 55 minutes'
  );

  -- Execution 2: Sent follow-up nudges
  v_execution_id_2 := gen_random_uuid();
  INSERT INTO kernel_executions (
    id,
    user_id,
    process_id,
    triggered_by,
    insight_id,
    parameters,
    status,
    items_processed,
    items_succeeded,
    items_failed,
    value_impact,
    summary,
    created_at,
    started_at,
    completed_at
  ) VALUES (
    v_execution_id_2,
    v_user_id,
    'send_followup_nudge',
    'automation',
    NULL,
    '{"message_tone": "warm"}'::jsonb,
    'completed',
    6,
    1,
    0,
    NULL,
    -- Hebrew: "Followed up with 6 quiet clients — 1 rebooked"
    'עקבתי אחרי 6 לקוחות שקטים — 1 קבע מחדש',
    now() - interval '3 hours',
    now() - interval '3 hours',
    now() - interval '2 hours 55 minutes'
  );

  -- Execution 3: Sent booking reminders
  v_execution_id_3 := gen_random_uuid();
  INSERT INTO kernel_executions (
    id,
    user_id,
    process_id,
    triggered_by,
    insight_id,
    parameters,
    status,
    items_processed,
    items_succeeded,
    items_failed,
    value_impact,
    summary,
    created_at,
    started_at,
    completed_at
  ) VALUES (
    v_execution_id_3,
    v_user_id,
    'send_reminder_sequence',
    'automation',
    NULL,
    '{"hours_before": 24}'::jsonb,
    'completed',
    3,
    3,
    0,
    NULL,
    -- Hebrew: "Sent 3 booking reminders for tomorrow's appointments"
    'שלחתי 3 תזכורות לפגישות של מחר',
    now() - interval '1 hour',
    now() - interval '1 hour',
    now() - interval '58 minutes'
  );

  RAISE NOTICE 'Created 3 kernel executions';

  -- ============================================================================
  -- INSERT KERNEL ACTION LOG (Feed entries for MyDaySection)
  -- ============================================================================

  INSERT INTO kernel_action_log (
    user_id,
    execution_id,
    process_id,
    triggered_by,
    summary,
    items_processed,
    items_succeeded,
    items_failed,
    value_impact,
    created_at
  ) VALUES
  (
    v_user_id,
    v_execution_id_1,
    'chase_overdue_invoices',
    'automation',
    'רדפתי אחרי 5 חשבוניות באיחור — 2 שילמו (₪2,480 נכנסו)',
    5,
    2,
    0,
    680.00,
    now() - interval '5 hours 55 minutes'
  ),
  (
    v_user_id,
    v_execution_id_2,
    'send_followup_nudge',
    'automation',
    'עקבתי אחרי 6 לקוחות שקטים — 1 קבע מחדש',
    6,
    1,
    0,
    NULL,
    now() - interval '2 hours 55 minutes'
  ),
  (
    v_user_id,
    v_execution_id_3,
    'send_reminder_sequence',
    'automation',
    'שלחתי 3 תזכורות לפגישות של מחר',
    3,
    3,
    0,
    NULL,
    now() - interval '58 minutes'
  );

  RAISE NOTICE 'Created 3 kernel action log entries';

  RAISE NOTICE 'Demo data seeding complete!';
  RAISE NOTICE '- 3 active insights (high/medium/low priority) in Hebrew';
  RAISE NOTICE '- 3 completed autonomous work entries in Hebrew';
  RAISE NOTICE '- 3 action log feed entries in Hebrew';
  RAISE NOTICE 'Refresh the Business OS dashboard to see the insights.';

END $$;
