-- The intake form a business actually owns.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- WHAT THIS REPLACES
--
-- `intake_form_templates` was a SYSTEM catalogue: no `user_id`, no RLS, eleven
-- seeded rows shared by every business, and the owner's only act was picking
-- one. Six of the platform's twenty-eight verticals had a template of their own;
-- everything else fell through to four generic shapes filed under 'other'.
--
-- That model cannot express the thing being built. A business cannot edit a row
-- it does not own, so per-question editing — by hand or by the assistant — has
-- nowhere to write. This table is that missing store: one form per business,
-- generated from what the platform already knows about them, owned by them.
--
-- WHY VERSIONS RATHER THAN ONE MUTABLE ROW
--
-- A form is edited after clients have already answered it. Overwriting the
-- questions in place would silently rewrite the questions of every submission
-- that referenced them — an answer would sit under a question nobody was asked.
-- Publishing writes a new version and archives the old one, so a completed
-- intake always has the form it was completed against still on disk.
--
-- The owner never sees a version number. This is bookkeeping, not a feature.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS business_intake_forms (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  version       INTEGER NOT NULL DEFAULT 1,

  -- draft     — generated or edited, never sent to anyone
  -- published — the one form clients receive
  -- archived  — superseded by a later publish; kept so old answers stay readable
  status        TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft', 'published', 'archived')),

  -- IntakeQuestion[] — see lib/business-os/intake/types.ts.
  -- Single-language: the form belongs to one business and is written in theirs.
  questions     JSONB NOT NULL DEFAULT '[]',

  -- Null on a form the owner built by hand rather than one that was generated.
  generated_at  TIMESTAMPTZ,
  -- { source: 'llm' | 'fallback' | 'manual', model, vertical, subVertical, serviceIds }
  --
  -- `source` is what stops a silent fallback passing itself off as a successful
  -- generation — the same distinction WebsiteGenerationService reports as
  -- `contentSource`, recorded here so it survives past the request that made it.
  generated_from JSONB,

  published_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, version)
);

-- ONE published form per business, enforced by the database rather than by
-- whichever code path happens to publish. Two live forms is not a state the
-- product has an answer for: every resolver asks for "the" published form.
CREATE UNIQUE INDEX IF NOT EXISTS idx_business_intake_forms_one_published
  ON business_intake_forms(user_id)
  WHERE status = 'published';

-- The draft the review screen opens. Also at most one — "edit" means edit the
-- draft, and a second one would make that sentence ambiguous.
CREATE UNIQUE INDEX IF NOT EXISTS idx_business_intake_forms_one_draft
  ON business_intake_forms(user_id)
  WHERE status = 'draft';

COMMENT ON TABLE business_intake_forms IS
  'One intake form per business, generated by AI from the business profile and services, reviewed and published by the owner. Replaces the shared intake_form_templates catalogue.';
COMMENT ON COLUMN business_intake_forms.questions IS
  'IntakeQuestion[] in the business''s own language. See lib/business-os/intake/types.ts.';
COMMENT ON COLUMN business_intake_forms.status IS
  'draft = never sent; published = the form clients receive (at most one); archived = superseded, kept so completed submissions stay readable.';

ALTER TABLE business_intake_forms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users read own intake forms" ON business_intake_forms;
CREATE POLICY "Users read own intake forms" ON business_intake_forms
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users insert own intake forms" ON business_intake_forms;
CREATE POLICY "Users insert own intake forms" ON business_intake_forms
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users update own intake forms" ON business_intake_forms;
CREATE POLICY "Users update own intake forms" ON business_intake_forms
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users delete own intake forms" ON business_intake_forms;
CREATE POLICY "Users delete own intake forms" ON business_intake_forms
  FOR DELETE USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION touch_business_intake_forms()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_touch_business_intake_forms ON business_intake_forms;
CREATE TRIGGER trg_touch_business_intake_forms
  BEFORE UPDATE ON business_intake_forms
  FOR EACH ROW EXECUTE FUNCTION touch_business_intake_forms();

-- ─────────────────────────────────────────────────────────────────────────────
-- "Sent" becomes a column.
--
-- It was a SENTINEL: `intake_responses = {template_id:'', template_key:'pending',
-- responses:{}}`, written in three places purely so the journey could draw a
-- pending step. The reader that renders a completed submission then looked up
-- the template by an empty id and found nothing, so "requested" and "answered"
-- were told apart by inspecting a magic string inside a JSON blob.
--
-- Three states, and now each has somewhere real to live:
--   never asked   intake_sent_at IS NULL
--   asked         intake_sent_at IS NOT NULL, intake_completed_at IS NULL
--   answered      intake_completed_at IS NOT NULL
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE scheduling_bookings
  ADD COLUMN IF NOT EXISTS intake_sent_at TIMESTAMPTZ;

COMMENT ON COLUMN scheduling_bookings.intake_sent_at IS
  'When the intake request was emailed to the client. Replaces the template_key=''pending'' sentinel previously written into intake_responses.';

-- Clear the sentinels. They are indistinguishable from a real submission to
-- anything that does not know the magic string, and nothing should have to.
UPDATE scheduling_bookings
   SET intake_sent_at = COALESCE(intake_sent_at, updated_at),
       intake_responses = NULL
 WHERE intake_responses IS NOT NULL
   AND intake_responses->>'template_key' = 'pending';

-- ─────────────────────────────────────────────────────────────────────────────
-- Carry the questions into the answers that already exist.
--
-- An old submission stores `{template_id, template_key, responses}` — the
-- answers keyed by field, and the field LABELS in a table that is about to be
-- dropped. Left alone, a completed intake would render as "session goals" and
-- "current level": the keys, tidied, because that is all that would remain.
--
-- The template is still here for one more statement, so the labels come along
-- with the answers. After this, a submission is readable on its own, which is
-- the property the new shape has by design and this gives the old ones by hand.
--
-- Labels only. Choice questions stored the option's VALUE rather than its
-- label, and no mapping is carried across — for the affected rows every field
-- is free text, and inventing a lookup for a case that does not occur would be
-- more code than the thing it protects.
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE scheduling_bookings b
   SET intake_responses = b.intake_responses || jsonb_build_object(
         'questions',
         COALESCE((
           SELECT jsonb_agg(
                    jsonb_build_object(
                      -- The old field key becomes the question id, so it still
                      -- matches the keys the answers are stored under.
                      'id', f->>'key',
                      'label', COALESCE(
                        f->>('label_' || COALESCE(p.language, 'en')),
                        f->>'label_en',
                        f->>'key'
                      ),
                      'type', CASE f->>'type'
                                WHEN 'textarea' THEN 'long_text'
                                WHEN 'select'   THEN 'single_choice'
                                WHEN 'radio'    THEN 'single_choice'
                                WHEN 'checkbox' THEN 'multi_choice'
                                ELSE 'short_text'
                              END,
                      'required', COALESCE((f->>'required')::boolean, false)
                    )
                    ORDER BY ord
                  )
             FROM intake_form_templates t,
                  LATERAL jsonb_array_elements(t.fields) WITH ORDINALITY AS x(f, ord)
            WHERE t.id = (b.intake_responses->>'template_id')::uuid
         ), '[]'::jsonb)
       )
  FROM business_profiles p
 WHERE p.user_id = b.user_id
   AND b.intake_responses ? 'template_id'
   AND NOT (b.intake_responses ? 'questions');

-- ─────────────────────────────────────────────────────────────────────────────
-- The old catalogue goes.
--
-- Pre-launch: the only submissions referencing it are on a test account, so
-- there is no history to preserve and no migration to write. Submissions from
-- here on carry their own question snapshot, which is what makes them readable
-- independently of any table.
--
-- `template_id` is dropped from the settings first — it is the FK holding the
-- catalogue in place. `collect_during_booking` goes with it: the settings API
-- has accepted and silently discarded that field for some time, while a
-- deprecated resolver still gated the public form on it, so a business with the
-- flag false received an intake email whose link said there was no intake form.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE user_intake_settings
  DROP COLUMN IF EXISTS template_id,
  DROP COLUMN IF EXISTS collect_during_booking;

DROP TABLE IF EXISTS intake_form_templates;
