/**
 * The evaluator, tested the way a parser has to be.
 *
 * `AnswerRenderer.ts` warned that "a parser here is a source of wrong numbers
 * dressed as a feature". The warning is fair, and these are the tests that earn
 * the right to ignore it: a precedence bug is silent, plausible, and would put a
 * confident wrong figure in front of someone making a decision.
 *
 * Hand-written cases cannot find that class of bug. Randomised differential
 * testing can.
 */

import { evaluateExpression } from '../render/expression';

/** Every step resolves; individual tests override where it matters. */
const values: Record<string, number> = {
  's1.value': 523,
  's2.value': 408.33,
  's3.count': 7,
  's4.value': 0,
};
const lookup = (ref: string): number | null =>
  ref in values ? values[ref] : null;

describe('arithmetic', () => {
  it.each([
    ['1 + 2', 3],
    ['10 - 4', 6],
    ['3 * 4', 12],
    ['10 / 4', 2.5],
    ['1 + 2 * 3', 7], // precedence, not 9
    ['(1 + 2) * 3', 9],
    ['10 - 4 - 3', 3], // left-associative, not 9
    ['100 / 10 / 2', 5], // left-associative, not 20
    ['-5 + 8', 3],
    ['2 * -3', -6],
    ['((2))', 2],
  ])('%p = %p', (source, expected) => {
    expect(evaluateExpression(source, lookup)).toBeCloseTo(expected, 10);
  });

  it('resolves step references', () => {
    expect(evaluateExpression('s1.value', lookup)).toBe(523);
    expect(evaluateExpression('s3.count', lookup)).toBe(7);
  });

  it('computes the two derivations that motivated it', () => {
    // "what percent are refunds of revenue"
    expect(evaluateExpression('s1.value / s2.value', lookup)).toBeCloseTo(1.2808, 3);
    // "by what percent did revenue drop" — (s2-s1)/s2, which percent_of cannot express
    expect(evaluateExpression('(s2.value - s1.value) / s2.value', lookup)).toBeCloseTo(-0.2808, 3);
  });
});

describe('precedence, against an independent reference', () => {
  /*
   * The reference is JavaScript's own evaluator, used HERE AND ONLY HERE.
   *
   * Differential testing is the only way to be confident about precedence and
   * associativity across expressions nobody thought to write down. Production
   * never evaluates a string — that is the entire point of the tokenizer — but
   * a test comparing against a known-correct implementation is exactly what a
   * hand-rolled parser needs, and the input here is generated by this file
   * rather than received from anyone.
   */
  const OPS = ['+', '-', '*', '/'];

  const randomExpression = (rand: () => number, depth = 0): string => {
    const roll = rand();

    if (depth > 3 || roll < 0.35) {
      // A non-zero literal: division by zero is covered deliberately below, and
      // letting it appear at random would make failures hard to read.
      return String(Math.floor(rand() * 20) + 1);
    }

    const left = randomExpression(rand, depth + 1);
    const right = randomExpression(rand, depth + 1);
    const op = OPS[Math.floor(rand() * OPS.length)];
    const body = `${left} ${op} ${right}`;

    return roll < 0.6 ? `(${body})` : body;
  };

  /** Deterministic, so a failure is reproducible from the seed alone. */
  const seeded = (seed: number) => () => {
    seed = (seed * 1664525 + 1013904223) % 4294967296;
    return seed / 4294967296;
  };

  it('agrees with the reference on 2000 random expressions', () => {
    const rand = seeded(20260908);
    let checked = 0;

    for (let i = 0; i < 2000; i++) {
      const source = randomExpression(rand);

      // eslint-disable-next-line no-new-func -- test-only reference, see above
      const expected = new Function(`return (${source});`)() as number;
      if (!Number.isFinite(expected)) continue;

      const actual = evaluateExpression(source, lookup);

      expect({ source, actual }).toEqual({
        source,
        actual: expect.closeTo(expected, 8),
      });
      checked++;
    }

    // Proof the loop did work, rather than skipping everything.
    expect(checked).toBeGreaterThan(1900);
  });
});

describe('refuses rather than guessing', () => {
  it.each([
    ['1 / 0', 'division by zero'],
    ['0 / 0', 'NaN'],
    ['s4.value / s4.value', 'zero over zero from real steps'],
  ])('%p returns null (%s)', (source) => {
    expect(evaluateExpression(source, lookup)).toBeNull();
  });

  it('returns null when a referenced step has no value', () => {
    /*
     * The failure worth naming. A step that matched no rows has a null value,
     * and JS coerces null to 0 silently — `null - 5` is `-5`. Without this
     * check the chat would state a drop of 5 for a period with no revenue
     * figure at all: a real number, quietly about nothing.
     */
    const missing = (ref: string) => (ref === 's2.value' ? null : 100);

    expect(evaluateExpression('s1.value - s2.value', missing)).toBeNull();
    expect(evaluateExpression('s2.value', missing)).toBeNull();
  });

  it.each([
    ['', 'empty'],
    ['   ', 'whitespace'],
    ['1 +', 'trailing operator'],
    ['+ ', 'operator alone'],
    ['1 2', 'two expressions'],
    ['(1 + 2', 'unclosed'],
    ['1 + 2)', 'unopened'],
    ['()', 'empty parens'],
  ])('%p returns null (%s)', (source) => {
    expect(evaluateExpression(source, lookup)).toBeNull();
  });
});

describe('cannot reach anything', () => {
  /*
   * The tokenizer is the security boundary: there is no rule that produces an
   * identifier, so none of these can even become tokens.
   */
  it.each([
    's1.value.constructor',
    's1.value.__proto__',
    '__proto__',
    'constructor',
    'process.exit(1)',
    'require("fs")',
    '1; alert(1)',
    'globalThis',
    's1.value ** 2',
    'Math.max(1,2)',
    's1.email',
    's1.rows',
    '"1" + "2"',
    '1 & 2',
  ])('%p is rejected', (source) => {
    expect(evaluateExpression(source, lookup)).toBeNull();
  });

  it('only reaches steps the lookup chooses to resolve', () => {
    // Reference resolution is the caller's, so an expression naming a step that
    // is not in this plan resolves to nothing rather than to another plan's.
    expect(evaluateExpression('s9.value', lookup)).toBeNull();
  });
});

describe('bounds', () => {
  it('rejects an over-long source before tokenizing', () => {
    expect(evaluateExpression('1 + '.repeat(80) + '1', lookup)).toBeNull();
  });

  it('rejects nesting past the depth cap', () => {
    const deep = '('.repeat(20) + '1' + ')'.repeat(20);
    expect(evaluateExpression(deep, lookup)).toBeNull();
  });

  it('still allows ordinary nesting', () => {
    expect(evaluateExpression('((1 + 2) * (3 - 1)) / 2', lookup)).toBe(3);
  });
});
